### ISSUE TITLE
Optimization error detected with simple manual class creations calls using type(name, bases, dict)

### ISSUE THREAD

**Issue by kongsgard** [Nuitka/Nuitka#1226]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
 
```
0.6.16.4
Python: 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:15:57) [MSC v.1916 64 bit (AMD64)]
Executable: C:\tools\miniconda3\envs\processor\python.exe
OS: Windows
Arch: x86_64
  ```

* How did you install Nuitka and Python

  `conda install -c conda-forge nuitka`

* The specific PyPI names and versions

  Only ifcopenshell-python is relevant (the project compiles nicely without this dependency, and a clean install with only this dependency also fails in the same way):
`conda install -c conda-forge ifcopenshell==v0.6.0`

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

  The error occurs when trying to compile any script with the following import statement:
`import ifcopenshell`

* Provide in your issue the Nuitka options used

```
--onefile --remove-output --prefer-source-code --assume-yes-for-downloads --enable-plugin=anti-bloat --noinclude-setuptools-mode=nofollow --noinclude-pytest-mode=nofollow --plugin-enable=pylint-warnings --plugin-enable=pkg-resources --plugin-enable=numpy --windows-onefile-tempdir
```

* Note if this is a regression

  This does not seem to work in any versions of Nuitka.

* Consider getting commercial support

  We will consider getting a commercial subscription if there is a feasible solution to this issue. Apart from this dependency, Nuitka seems to work great!
  
* Relevant part of the command line output:

```
Problem with statement at C:\tools\miniconda3\envs\processor\lib\site-packages\ifcopenshell\entity_instance.py:30:
-> try:
Problem with statement at C:\tools\miniconda3\envs\processor\lib\site-packages\ifcopenshell\entity_instance.py:32:
-> except ImportError as e:
Problem with statement at C:\tools\miniconda3\envs\processor\lib\site-packages\ifcopenshell\entity_instance.py:30:
-> try:
Problem with statement at C:\tools\miniconda3\envs\processor\lib\site-packages\ifcopenshell\entity_instance.py:30:
-> try:
Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\tools\\miniconda3\\envs\\processor\\lib\\site-packages\\ifcopenshell\\entity_instance.py', 'module_name': <ModuleName ifcopenshell.entity_instance>, 'code_flags': ''}>'.
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\__main__.py", line 187, in <module>
    main()
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\__main__.py", line 173, in main
    MainControl.main()
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\MainControl.py", line 709, in main
    main_module = _createNodeTree(filename=filename)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\MainControl.py", line 174, in _createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\optimizations\Optimization.py", line 362, in optimize
    finished = makeOptimizationPass()
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\optimizations\Optimization.py", line 325, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\optimizations\Optimization.py", line 220, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\optimizations\Optimization.py", line 118, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 530, in computeModule
    result = module_body.computeStatementsSequence(
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\nodes\StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 558, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\nodes\TryNodes.py", line 154, in computeStatement
    result = except_handler.computeStatementsSequence(
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 558, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\nodes\TryNodes.py", line 98, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 558, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 569, in computeStatement
    branch_yes_collection.computeBranch(branch=yes_branch)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 828, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 558, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\tools\miniconda3\envs\processor\lib\site-packages\nuitka\nodes\TryNodes.py", line 141, in computeStatement
    raise NuitkaOptimizationError(
nuitka.Errors.NuitkaOptimizationError:
This statement does raise but didn't annotate an exception exit.
    <node kind="StatementAssignmentVariable" line="33" variable_name="logging" is_temp="False" var_type="object" owner="ifcopenshell$entity_instance">
      <role name="source">
        <node kind="ExpressionBuiltinType3" line="33">
          <role name="type_name">
            <node kind="ExpressionConstantStrRef" line="33" constant="'logger'" user_provided="True" />
          </role>
          <role name="bases">
            <node kind="ExpressionConstantTupleRef" line="33" constant="(&lt;class 'object'&gt;,)" user_provided="True" />
          </role>
          <role name="dict">
            <node kind="ExpressionMakeDict" line="33">
              <role name="pairs" type="list">
                <node kind="ExpressionKeyValuePair" line="33">
                  <role name="key">
                    <node kind="ExpressionConstantStrRef" line="33" constant="'exception'" user_provided="True" />
                  </role>
                  <role name="value">
                    <node kind="ExpressionBuiltinStaticmethod" line="33">
                      <role name="value">
                        <node kind="ExpressionFunctionCreation" line="33">
                          <role name="defaults" type="list" />
                          <role name="kw_defaults" type="none" />
                          <role name="annotations" type="none" />
                          <role name="function_ref">
                            <node kind="ExpressionFunctionRef" line="33" code_name="ifcopenshell$entity_instance$$$function__1_lambda" />
                          </role>
                        </node>
                      </role>
                    </node>
                  </role>
                </node>
              </role>
            </node>
          </role>
        </node>
      </role>
    </node>
The above information should be included in a bug report.
```

**Comment by kayhayen** [comment]
Minimal reproducer for this is actually only this: 

```
try:
    import logging
except ImportError as e:
    logging = type("logger", (object,), {"exception": staticmethod(lambda s: print(s))})
```

So far, `type` with 3 arguments, which is used to create a new class, doesn't annotate an exception exit. In this case, both bases and dictionary creation cannot fail, but the `type3` defaults to saying it does raise an exception, but doesn't say which. I am now checking, if we can also annotate when it really doesn't have a chance to raise. This particular one would be out of the question.

Obviously the code itself is strange, as the `ImportError` seems unlikely to occur with any Python really.

**Comment by kayhayen** [comment]
This is fixed on factory https://nuitka.net/doc/factory.html

I have explored a bit, how the metaclass selection could be done at runtime, and actually had some success for at least some Python versions. It will naturally be very nice to integration that into standard class building.

**Comment by kongsgard** [comment]
Thanks for the quick response!
This might not be related to the original issue, but while I'm now able to successfully compile the example above, I'm still not able to run the resulting executable: 

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\ONCD6B~1\ifcopenshell\ifcopenshell_wrapper.py", line 14, in swig_import_helper
  File "importlib.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ifcopenshell._ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\ONCD6B~1\ifcopenshell\__init__.py", line 43, in <module ifcopenshell>
  File "C:\Users\user\AppData\Local\Temp\ONCD6B~1\ifcopenshell\ifcopenshell_wrapper.py", line 17, in <module ifcopenshell.ifcopenshell_wrapper>
  File "C:\Users\user\AppData\Local\Temp\ONCD6B~1\ifcopenshell\ifcopenshell_wrapper.py", line 16, in swig_import_helper
  File "importlib.py", line 127, in import_module
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\ONCD6B~1\ifcopenshell\__init__.py", line 51, in <module ifcopenshell>
ImportError: IfcOpenShell not built for 'windows\64bit\python3.8'
```

**Comment by kayhayen** [comment]
Please report other issues in a new reports, otherwise I get too confused.

**Comment by kayhayen** [comment]
Part of 0.6.17.2 hotfix release.
