### ISSUE TITLE
Error: ld.exe: cannot find ltrans0.ltrans.o: No such file or directory

### ISSUE THREAD

**Issue by mrkio9** [Nuitka/Nuitka#1469]
**im trying to pack my file with:**
_"python -m nuitka --mingw64 --windows-icon-from-ico=bomb.ico --onefile --windows-company-name=project --windows-product-version=1.0 --plugin-enable=tk-inter --plugin-enable=numpy --follow-imports  --include-package-data=selenium --show-modules --show-scons --show-progress myproject.py"_ 

but it always error: 
**collect2.exe: error: ld returned 1 exit status
scons: *** [C:\users\admin\desktop\KAISAS~1\_KAISA~1.DIS\myproject.exe] Error 1
scons: internal stack trace:**

File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Job.py", line 262, in run
    task.execute()
  File "...\scons-4.3.0\SCons\Script\Main.py", line 193, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "...\scons-4.3.0\SCons\Taskmaster.py", line 235, in execute
    self.targets[0].build()
  File "...\scons-4.3.0\SCons\Node\__init__.py", line 755, in build3.0\SCons\Node\__init__.py", line 755, in build
    self.get_executor()(self, **kw)                                                                          3.0\SCons\Executor.py", line 384, in __call__
  File "...\scons-4.3.0\SCons\Executor.py", line 384, in __call__                                                                3.0\SCons\Executor.py", line 120, in execute_action_list
    return _do_execute_map[self._do_execute](self, target, kw)
  File "...\scons-4.3.0\SCons\Executor.py", line 120, in execute_action_list
    **raise status    # TODO pylint E0702: raising int not allowed
scons: building terminated because of errors.**

c:/users/admin/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Admin\AppData\Local\Temp\ccpqfFcm.ltrans0.ltrans.o: No such file or directory
c:/users/admin/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Admin\AppData\Local\Temp\ccpqfFcm.ltrans1.ltrans.o: No such file or directory
c:/users/admin/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Admin\AppData\Local\Temp\ccpqfFcm.ltrans2.ltrans.o: No such file or directory
c:/users/admin/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Admin\AppData\Local\Temp\ccpqfFcm.ltrans3.ltrans.o: No such file or directory
c:/users/admin/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Admin\AppData\Local\Temp\ccpqfFcm.ltrans4.ltrans.o: No such file or directory
c:/users/admin/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\Admin\AppData\Local\Temp\ccpqfFcm.ltrans5.ltrans.o: No such file or directory

**please help me solve my problems. i cannot fix it 

my Nuitka version**
0.7.3
Commercial: None
Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Admin\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

**Comment by kayhayen** [comment]
Looks like a bug of the C compiler. Is this repeatable?

**Comment by iindexx** [comment]
> Looks like a bug of the C compiler. Is this repeatable?

Hello i'm have same problem:

C:\Users\sashu85>python -m nuitka --follow-imports c:\python\clipboard.py
Nuitka-Options:INFO: Used command line options: --follow-imports c:\python\clipboard.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.7.6' on Python '3.10' commercial None.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program (no progress information available).
c:/users/sashu85/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\sashu85\AppData\Local\Temp\cc2nxgIf.ltrans0.ltrans.o: No such file or directory
c:/users/sashu85/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\sashu85\AppData\Local\Temp\cc2nxgIf.ltrans1.ltrans.o: No such file or directory
c:/users/sashu85/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\sashu85\AppData\Local\Temp\cc2nxgIf.ltrans2.ltrans.o: No such file or directory
c:/users/sashu85/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\sashu85\AppData\Local\Temp\cc2nxgIf.ltrans3.ltrans.o: No such file or directory
c:/users/sashu85/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\sashu85\AppData\Local\Temp\cc2nxgIf.ltrans4.ltrans.o: No such file or directory
c:/users/sashu85/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\sashu85\AppData\Local\Temp\cc2nxgIf.ltrans5.ltrans.o: No such file or directory
c:/users/sashu85/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\sashu85\AppData\Local\Temp\cc2nxgIf.ltrans6.ltrans.o: No such file or directory
c:/users/sashu85/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\sashu85\AppData\Local\Temp\cc2nxgIf.ltrans7.ltrans.o: No such file or directory
c:/users/sashu85/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\sashu85\AppData\Local\Temp\cc2nxgIf.ltrans8.ltrans.o: No such file or directory
c:/users/sashu85/appdata/local/nuitka/nuitka/gcc/x86_64/11.2.0-12.0.1-9.0.0-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\sashu85\AppData\Local\Temp\cc2nxgIf.ltrans9.ltrans.o: No such file or directory
collect2.exe: error: ld returned 1 exit status
scons: *** [C:\Users\sashu85\clipboard.exe] Error 1

**Comment by kayhayen** [comment]
The only way I think this could happen is if a compilation was running twice, with one cleaning up the build stage while the other is the one you are seeing. On the other hand though, these look like generated temp file names, that would have to be unique, and not overlap.

**Comment by iindexx** [comment]
> The only way I think this could happen is if a compilation was running twice, with one cleaning up the build stage while the other is the one you are seeing. On the other hand though, these look like generated temp file names, that would have to be unique, and not overlap.

I'm try it run many times eith same result.

**Comment by kayhayen** [comment]
The only thing I can really do is to update the MinGW64, which is on factory now, please give it a try: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
The updated MinGW64 is on the develop branch now, not sure of course if it helps, but there is not a lot I can do about MinGW64 errors.

**Comment by kayhayen** [comment]
Guessing that the issue is fixed, nobody has reported it anymore.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.

**Comment by Craftonix** [comment]
Hello,
I still have this issue.
Test with normal pip install, develop branch, factory branch.
Cleaned mingw downloaded, nuitka redownload and install it.

but still have : 
 c:/users/yl/appdata/local/nuitka/nuitka/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find c:\temp\cc6jiaVi.ltrans0.ltrans.o: No such file or directory
c:/users/yl/appdata/local/nuitka/nuitka/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find c:\temp\cc6jiaVi.ltrans1.ltrans.o: No such file or directory
c:/users/yl/appdata/local/nuitka/nuitka/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find c:\temp\cc6jiaVi.ltrans2.ltrans.o: No such file or directory
collect2.exe: error: ld returned 1 exit status

Any idea how to fix that ?
Can you reopen the ticket ?

**Comment by kayhayen** [comment]
@Craftonix can you provide information, what `PATH` also contains? Nuitka adds the downloaded MinGW64 to start of `PATH`, with more information, please create a new ticket with full issue template.

Since this is about temp files, it's strange. What's more strange is the use of `c:\temp` which seems non-standard, and makes me question the environment.

**Comment by Craftonix** [comment]
Hello kayhayen,
I'm not sure what was the guilty path, because made some clean up, on many gcc i have (codeblocks, msys), after cleaning up the path, it started working again.
C:\temp is a not standard yes, i just don't like having bunch of temp file in user directory, more easy to browser and clean.
