### ISSUE TITLE
Javapath error when trying to create a distributable standalone

### ISSUE THREAD

**Issue by DimoDimchev** [Nuitka/Nuitka#1715]
I installed Nuitka using pip and ran the following command for my project: 
```python -m nuitka --standalone --include-plugin-directory=plugins --enable-plugin=tk-inter --enable-plugin=numpy main.py --``` 

After a while I get the following error:
```
Nuitka-Plugins:INFO: numpy: Found 1 file DLLs from numpy installation.
Nuitka-Plugins:INFO: numpy: Found 28 files DLLs from scipy installation.
Detecting used DLLs: 0.0%|                         | 0/118, GNDV_main.exeTraceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "C:\Program Files\Python37\lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "C:\Program Files\Python37\lib\site-packages\nuitka\MainControl.py", line 966, in main
    source_dir=OutputDirectories.getSourceDirectoryPath(),
  File "C:\Program Files\Python37\lib\site-packages\nuitka\freezer\Standalone.py", line 701, in detectUsedDLLs
    standalone_entry_point=standalone_entry_point, source_dir=source_dir
  File "C:\Program Files\Python37\lib\site-packages\nuitka\freezer\Standalone.py", line 669, in _detectUsedDLLs
    update_cache=not Options.shallNotStoreDependsExeCachedResults(),
  File "C:\Program Files\Python37\lib\site-packages\nuitka\freezer\Standalone.py", line 582, in _detectBinaryDLLs
    update_cache=update_cache,
  File "C:\Program Files\Python37\lib\site-packages\nuitka\freezer\DllDependenciesWin32.py", line 88, in detectBinaryPathDLLsWindowsDependencyWalker
    scan_dirs = _getScanDirectories(package_name, original_dir)
  File "C:\Program Files\Python37\lib\site-packages\nuitka\freezer\DllDependenciesWin32.py", line 141, in _getScanDirectories
    if not any(listDllFilesFromDirectory(scan_dir)):
  File "C:\Program Files\Python37\lib\site-packages\nuitka\utils\FileOperations.py", line 405, in listDllFilesFromDirectory
    for fullpath, filename in listDir(path):
  File "C:\Program Files\Python37\lib\site-packages\nuitka\utils\FileOperations.py", line 275, in listDir
    [(os.path.join(path, filename), filename) for filename in os.listdir(real_path)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath'
```

What could be causing this? When I went to the specified path the shortcut that is javapath is indeed broken. How can I fix this and why is Java even needed here in the first place?

Here's my version info:
```
1.0
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Program Files\Python37\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**Comment by kayhayen** [comment]
So, you have a directory in `PATH` that Nuitka is attempting to find out, if it has any DLLs in there, but then doesn't recognize that a non-existant directory fails to list.

**Comment by kayhayen** [comment]
This is fixed in https://nuitka.net/doc/factory.html and will become part of 1.0.2

**Comment by DimoDimchev** [comment]
Is it safe to use that branch or should I wait for the changes to go to develop at least?

**Comment by DimoDimchev** [comment]
I tried running this off the factory branch but the same error still persists

**Comment by kayhayen** [comment]
Wait, it says `The system cannot find the path specified`  so it seemed it wouldn't exist, are you saying you have a corrupted file system or something like that?

**Comment by DimoDimchev** [comment]
The folder does exist, but when trying to open it I get the following pop-up, so yes I guess it's corrupted
![Screenshot 2022-08-04 144520](https://user-images.githubusercontent.com/38102582/183050031-af1a5ccb-80ee-4a9c-93cb-c95582135a44.png)

**Comment by DimoDimchev** [comment]
I've removed that directory from PATH, and trying again now, I think this can be closed.

**Comment by kayhayen** [comment]
In order to handle this for future users, I am ignoring `OSError` from the attempt to list a `PATH` element. This is very strange one, maybe a permission issue, but for things in `PATH` that is strange, but clearly that folder normally is intended for Java only, from what I know, so maybe it is a wrong `PermissionError` of some sorts in Windows there, or just a corruption.

Anyway, indeed closing it, too unlikely to relevant for real, but I am now assuming, it would have just worked for you, and that is always good given the large number of users.

**Comment by kayhayen** [comment]
Release as part of hotfix 1.0.2, but a newer one should be used, that one still had critical errors.
