### ISSUE TITLE
pkgutil.walk_packages is empty

### ISSUE THREAD

**Issue by nerdvegas** [Nuitka/Nuitka#183]
Installed via pip:
0.6.0.4
Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
Executable: /usr/bin/python
OS: Linux
Arch: x86_64

Given a package like so:
```
foo/
  __init__.py
  bah/__init__.py
```

Without nuitka, I get:
```
>>> import foo, pkgutil
>>> print list(pkgutil.walk_packages(foo.__path__))
[(<pkgutil.ImpImporter instance at 0x7fc4189fcf80>, 'bah', True)]
```

However, when I run the same, on `foo.so` created via `nuitka --module --include-package=foo foo`, I get:
```
>>> import foo, pkgutil
>>> print list(pkgutil.walk_packages(foo.__path__))
[]
```

**Comment by kayhayen** [comment]
So adding `iter_module` as an empty stub did nothing at all. There are btw also no examples really in the source code or documentation how this should work. Also `sys.path_importer_cache` is only described as a speedup measure to avoid repeated scans. As such, it may well useful, but I don't think so.

However, calling that will be necessary, so I added first code to the meta path based importer of Nuitka that for packages adds itself as the value there and that doesn't get used of course, because the top level module is imported by the standard extension module importer, only names below.

So I also added code for at the end of the module, which is run if it's a package, that adds the module to the registry, and then it works, my `iter_module` is getting called. Right now returns an empty list, same as before, but now there is a place to fix it.

I need to clean this up, so code template can know it's top level package, and only do it then, that should clear things up, so it's not done twice and for each package.

Also I am a bit uncertain how this is supposed to work in case of `__path__` being extended by the environment variable for plugin tests into it. I do think in this instance, things will automatically do the right thing with both `__path__` elements being walked and yielding the results.

**Comment by kayhayen** [comment]
So I got the the `is_top` logic sorted out, and now trying to implement `iter_modules` there is only a `prefix` passed, whereas currently the importer only knows about module names. So I am a bit at loss there, how to approach this.

Seems this code needs to become a lot more friends with the values `__path__` is going to have for at least the top level module, and then take it from there. Maybe Nuitka needs its own kind of registry for the `__path__` to module name reversal. Alternatively I could hunt through `sys.modules` for matching compiled modules, checking their `__path__` and then going from their full name from `__name__` and `__package__`, to see what we got below that namespace.

The later might be somewhat hacky, but ought to work without extra storage. It's also unclear to me, if `walk_packages` should be working recursively, i.e. descend into sub packages and list those too or not. Any idea about that part @nerdvegas, this is all not too well documented.

**Comment by kayhayen** [comment]
Ah my bad, the prefix is some rather strange thing, where `iter_modules` is supposed to put it in front of module names, for whatever reason, that is the job of it too. So a full dump of everything will be needed, and that's easy enough.

**Comment by kayhayen** [comment]
So this ought to be working. I am going to apply more polish, but it ought to work for you. Can you try this out:

http://nuitka.net/doc/factory.html

**Comment by nerdvegas** [comment]
This works on my small test. Will get back to my main project soon and will
let you know how I get on.

Thanks for the awesome work and quick turnaround, nuitka could be very
beneficial to my own OSS project. I have a particular need to package some
tools up into standalone executables, and any performance improvement will
be very welcome also.

Thx
Allan

**Comment by nerdvegas** [comment]
Hi Kay,

I'm getting problems still. Consider:

```
]$ find
./foo
./foo/__init__.py
./foo/pkg1
./foo/pkg1/__init__.py
./foo/pkg1/mod_a.py
./foo/pkg1/mod_b.py
./foo/pkg2
./foo/pkg2/__init__.py
./foo/pkg2/mod_c.py
./foo/pkg2/mod_d.py
```
And script, run in same dir:
```
# test.py
import pkgutil
from importlib import import_module
pkg = import_module("foo")
it = pkgutil.iter_modules(pkg.__path__)
for r in it:
    print r
```
Non-nuitka output:
```
]$ python test.py 
(<pkgutil.ImpImporter instance at 0x7f5614d9c8c0>, 'pkg1', True)
(<pkgutil.ImpImporter instance at 0x7f5614d9c8c0>, 'pkg2', True)
```
Nuitka output:
```
]$ python test.py 
(<class 'importlib._nuitka_compiled_modules_loader'>, 'pkg1', True)
(<class 'importlib._nuitka_compiled_modules_loader'>, 'pkg1.mod_a', False)
(<class 'importlib._nuitka_compiled_modules_loader'>, 'pkg1.mod_b', False)
(<class 'importlib._nuitka_compiled_modules_loader'>, 'pkg2', True)
(<class 'importlib._nuitka_compiled_modules_loader'>, 'pkg2.mod_c', False)
(<class 'importlib._nuitka_compiled_modules_loader'>, 'pkg2.mod_d', False)
```

In my own project, I'm seeing some other strange things too.

I have some packages like so:
```
rezplugins.package_repository
rezplugins.build_process
...
```
When I iterate over `iter_modules` on pkg `rezplugins.package_repository`, I get a recursive walk (as per my simple example), but as if it's iterated over `rezplugins`! Ie, it includes modules within `rezplugins.build_process` etc.

I also see some odd paths in `__path__`, but I don't know if this has anyting to do with nuitka:
```
>>> import rezplugins.package_repository
>>> rezplugins.package_repository.__path__
['./rezplugins/package_repository', '/notexist/package_repository', '/notexist']
```

Hope this info is useful,
Allan

**Comment by nerdvegas** [comment]
ps - I think you may also be adding an extra `.` to `prefix`, I am seeing modules returned like `foo..bah` when prefix is `foo.`

**Comment by nerdvegas** [comment]
pps - I may be able to work around this problem temporarily while you figure this out. In order to do so, and keep my code compatible with its standard non-nuitka build at the same time, it would be amazing if nuitka could perhaps inject something into the packages that it has compiled, so I can put conditionals in around nuitka's presence. Clearly this would not be necessary in an ideal world, but such a feature may help during adoption.

Thx
A

**Comment by kayhayen** [comment]
I removed the dot from the prefix. I was not sure what values are given there, with or without the dot, so I added them, but seems that as no good. I pushed the fix for that to factory.

I am now checking how to be non-recursive. I feel, I am not getting any indication of which modules to provide, as prefix is empty, and we are the being same loader for all these instances. Maybe it takes a dedicated object of a new class to carry the original package name, then it seems doable.

Also, I had to disable the feature for pure accelerated mode, as `multiprocessing` is partially compiled, partially from this, so this only works for standalone mode and module (package really) mode now.

And the "/doesnotexit" paths come from Nuitka injecting into `__path__` of packages via environment variables, with that as a default. This is about the `py.test` integration that works this way, but is a bit ugly there, in that it does `os.environ.get(..., "/doesnotexist") rather than a proper `if ... in os.environ: __path__.append(...)`. That is mostly me being lazy to neither document it and not completing it to be sensible. I will address that shortly after I get the more important thing working. This is more of a nuisance.

I will take your example therefore as a `tests/package` test and make it cover the output. I think going to dedicated objects might be the right way already, then allowing to filter according to a `self.package_name` and that properly being a prefix to the name, but no remaining `.` so we are not being recursive, and then be good. Could be easy now.

Getting the partial compilation of multiprocessing to work could also well be about proper `__path__`, at least putting something in the importer cache for that real one, was harmful, preventing loads of modules below the package from disk with at least Python3. So it seems, the object we put there, better also knows how to do stuff.

As for detecting Nuitka, that is the one thing I want to be unnecessary. I will try and solve this with high priority.

**Comment by kayhayen** [comment]
Sorry for the delay, but I intend to solve this during my "week of bugfixes" right now, hopefully for the next release.

**Comment by kayhayen** [comment]
Just to record my idea, I think I found that I would have to have dedicated instances per module as their loaders, so they have an attribute where they came from. No longer sure though, if this was really necessary. As a first step I added your test to see it failing.

**Comment by nerdvegas** [comment]
Cheers! Still keen on continuing on with this work once the problems are
ironed out.
A

**Comment by kayhayen** [comment]
So I just pushed stuff to factory that enhances this.

* The meta path based importer is now also used as instances in the path importer cache, so it knows what to filter for and then limits its output.

* It also is done for mere binaries now, which is how I will test it, there is no point in doing it only for standalone and modules, binaries will be able to use it too.

* For the tests it is now possible to require runtime path for accelerated programs, so they cannot see the original Python code, in which case those ones win for pkgutil.iter_modules which is not showing anything.

* The way the class is created, doesn*t work for Python3 to make the PyCFunction methods, and so
  the constructor call fails badly, which is ignored for now. So this works for Python2 only.

I think that this might be what I will do for the next release. I noticed you use Python2 only, so your side of the report will be dealt with. I will have to introduce a proper Python type for the meta path based importer so it can have a constructor and iter_modules method that works in Python3 too. But for now, I am too annoyed at how long this took and move on to the other issues.

So this will means, you can try it and it will be in 0.6.1 for Python2 and hopefully 0.6.2 for Python3.

**Comment by nerdvegas** [comment]
The iter_modules func isn't returning any modules. Simple test attached.

Thx
A

**Comment by kayhayen** [comment]
I changed it so that --experimental=pkgutil_itermodules activates the code. Can you try with that?

**Comment by nerdvegas** [comment]
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    for r in it:
  File "/usr/lib/python2.7/pkgutil.py", line 147, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "/usr/lib/python2.7/pkgutil.py", line 53, in wrapper
    return func(*args, **kw)
  File "/usr/lib/python2.7/pkgutil.py", line 157, in iter_importer_modules
    return importer.iter_modules(prefix)
TypeError: unbound method iter_modules() must be called with
_nuitka_compiled_modules_loader instance as first argument (got str
instance instead)
```

**Comment by nerdvegas** [comment]
It seems like maybe you need a unit test specifically for plugin-related
functionality (iter_modules etc)? Maybe start with my simple test here - ie
check that native python's iter_modules/iter_packages results matches
Nuitka's.

Cheers
A

**Comment by kayhayen** [comment]
Seems I went too far towards Python3, so now I started making it a type. Annoying work, but necessary to get this right.

**Comment by kayhayen** [comment]
So I made the change to have a proper type for instantiation for the meta path based loader, but I only got so far to make sure it's not a regression. No idea if that improves the situation. It might, but I didn't check, I hope I will before the release this weekend.

**Comment by kayhayen** [comment]
It is in the release, and I think it might work already. I am right now working to make it active by default.

**Comment by kayhayen** [comment]
So I did this, but it seems to be problematic for partial package compilations, and multiprocessing, for reasons I have not yet indentified. It may be that the loader of Nuitka needs to be able to defer to the other loaders itself, they might not get asked, if they are not the loader of the containing package, despite `__path__`.

So this has a lot of consequences it seems.

**Comment by kayhayen** [comment]
So I did this, but it seems to be problematic for partial package compilations, and multiprocessing, for reasons I have not yet indentified. It may be that the loader of Nuitka needs to be able to defer to the other loaders itself, they might not get asked, if they are not the loader of the containing package, despite `__path__`.

I need to debug this some more, but it seems this is doable for next release.

**Comment by kayhayen** [comment]
This appears ready for release, partial package compilation seems questionable, therefore I chose to simply make it so that multiprocessing plugin includes whole package parts it needs.

**Comment by nerdvegas** [comment]
Hey Kay, thanks for getting back to me! Just so you're aware I won't have
time to try this out for the next few weeks, but I'll get there.
Thanks again
Allan

**Comment by kayhayen** [comment]
I have had the chance to use it with Django, where it worked for a compiled package, so it cannot be all that bad. For now I am assuming it's good. Let me know if it works for you too.

The partial compilation seems to be a unrelated bug, that has been found meanwhile, no worries anymore about this from me.

**Comment by kayhayen** [comment]
Released as 0.6.5
