### ISSUE TITLE
opencv + nuitka = fail on compile, since version 1.3.1

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#1992]
Lets consider small demo project
[nuitka-trouble-opencv-python.zip](https://github.com/Nuitka/Nuitka/files/10377658/nuitka-trouble-opencv-python.zip)

* ```setup-demo.sh```  setup up pipenv environment with opencv and nuitka==1.2.7
* ```demo_failed_build.sh``` should successfully compile ```test.py``` and build  executable (see ``build-nuitka-1.2.7-OK.log``)

then lets setup any version of nuitka > 1.3 with ``setup-nuitka.sh`` and call again
``demo_failed_build.sh`` — and we got some fail on compile:

* ``build-nuitka-1.3.1.log`` / ``build-nuitka-1.3.2.log``
```
  File "/home/stas/projects/nuitkas/nuitka-trouble-opencv-python/.venv/lib64/python3.10/site-packages/nuitka/plugins/standard/OptionsNannyPlugin.py", line 139, in getImplicitImports
    if self.evaluateCondition(
  File "/home/stas/projects/nuitkas/nuitka-trouble-opencv-python/.venv/lib64/python3.10/site-packages/nuitka/plugins/PluginBase.py", line 1098, in evaluateCondition
    result = eval(condition, context)
  File "<string>", line 1, in <module>
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
```

* ``build-nuitka-1.3.2.log`` / ``build-nuitka-1.3.3.log`` / ``build-nuitka-1.3.4.log`` / ``build-nuitka-1.3.6.log``
```
FATAL: options-nanny: Error, failed to evaluate condition 'version("opencv-python") < (4,6)' in this context, exception was ''<' not supported between instances of 'NoneType' and 'tuple''.
```

**Comment by kayhayen** [comment]
Now what is striking me here is `opencv_python_headless` which seems to be another name to get `cv2` from. Also this must mean that `cv2.__version__` is not yet. You are the second one to report this, but also you maybe saw, so far we only got the message added, to know what was the complaint.

**Comment by kayhayen** [comment]
At least the fallback is not working, 

>>> cv2.__version__
'4.7.0'

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

Also, there is a workaround that I kind of hate to recommend. You can disable the options-nanny plugin, until 1.3.8 is released.

**Comment by belonesox** [comment]
Factory «works» on this «toy example», I will check now it on my working projects...

**Comment by belonesox** [comment]
On my real projects, factory branch («1.4rc8») is still not OK (possible not related to the issue).

```

Traceback (most recent call last):
  File "/home/stas/projects/prod-project/.venv/src/nuitka/nuitka/__main__.py", line 151, in <module>
    main()
  File "/home/stas/projects/prod-project/.venv/src/nuitka/nuitka/__main__.py", line 137, in main
    MainControl.main()
  File "/home/stas/projects/prod-project/.venv/src/nuitka/nuitka/MainControl.py", line 939, in main
    main_module = _createMainModule()
  File "/home/stas/projects/prod-project/.venv/src/nuitka/nuitka/MainControl.py", line 211, in _createMainModule
    Recursion.checkPluginPath(
  File "/home/stas/projects/prod-project/.venv/src/nuitka/nuitka/importing/Recursion.py", line 335, in checkPluginPath
    if os.path.isfile(plugin_info[0]) or Importing.isPackageDir(plugin_info[0]):
  File "/usr/lib64/python3.10/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```

So I will wait new nuitka release, to isolate and minimize reproduction case....

**Comment by demishu** [comment]
I met the same matter with --standalone

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

Also, there is a workaround that I kind of hate to recommend. You can disable the options-nanny plugin, until 1.3.8 is released.

**Comment by kayhayen** [comment]
@belonesox yes, please isolate the other issue, I am preparing a 1.3.8, you can try the branch already now, similar to factory, let me know a reproducer and I might be able to include it already.

**Comment by demishu** [comment]
> @belonesox yes, please isolate the other issue, I am preparing a 1.3.8, you can try the branch already now, similar to factory, let me know a reproducer and I might be able to include it already.

Thank you so much. I compiled it correctly, love you, and have a good day

**Comment by kayhayen** [comment]
@demishu love you back :)

**Comment by kayhayen** [comment]
This is part of the 1.4 release, I forgot to clear it with 1.3.8 I believe.
