### ISSUE TITLE
Built exe fails with ModuleNotFoundError when importing tkinterweb

### ISSUE THREAD

**Issue by lalitdagre** [Nuitka/Nuitka#1998]
I am using Nuitka to package a Python application that uses TKinterweb Python package. 

The command to build package is 

```
python.exe -m nuitka --mingw64 --standalone --onefile --windows-company-name=webview --include-module=tkinterweb.bindings --include-package=tkinterweb --follow-import-to=
tkinterweb --follow-imports --windows-product-version=2 --plugin-enable=pkg-resources --enable-plugin=tk-inter --include-package-data=tkinterweb --remove-output webview.py
```

On executing the built exe, the following error is displayed

```
ModuleNotFoundError: The files required to run TkinterWeb could not be found. This usually occurs when bundling TkinterWeb into an app without forcing the application maker to include all nessessary files. See https://github.com/Andereoo/TkinterWeb/blob/main/tkinterweb/docs/FAQ.md for more information.

Error: Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Local\webview\webview\200~1.0\tkinterweb\__init__.py", line 32, in <module tkinterweb>
ModuleNotFoundError: No module named 'bindings'
```

Previously I was using PyInstaller with the `--collect-all` option and it was working.

* Nuitka version

  > python -m nuitka --version
0.6.14.4
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
Executable: D:\office\work\py3.7.9-32-venv\Scripts\python.exe
OS: Windows
Arch: x86

* How did you install Nuitka and Python

  pip install nuitka on windows 10

* The specific PyPI names and versions

  > python -m pip freeze
future==0.18.2
Nuitka==0.6.14.4
pefile==2019.4.18
Pillow==7.1.2
PyGetWindow==0.0.8
pywin32==228
pywin32-ctypes==0.2.0
requests==2.23.0
six==1.15.0
tk-html-widgets==0.4.0
tkinterweb==3.15.6
urllib3==1.25.9
WMI==1.5.1

The import statement in the code is

```
import tkinterweb

try:
  import tkinter as tk      # python3
except ImportError:
  import Tkinter as tk     # python2

root = tk.Tk() #create the Tkinter window
root.mainloop()
```

**Comment by Maxwell175** [comment]
Can you please try again with the latest version of Nuitka from pip? The latest version currently is 1.3.7

**Comment by kayhayen** [comment]
Updated Nuitka is available on conda-forge. We added lots of support for Tk packages, I forgot if this one would be among them.

**Comment by lalitdagre** [comment]
> Can you please try again with the latest version of Nuitka from pip? The latest version currently is 1.3.7

I have tested it with Nuitka 1.3.7 but still getting error.

```
ModuleNotFoundError: The files required to run TkinterWeb could not be found. This usually occurs when bundling TkinterWeb into an app without forcing the application maker to include all nessessary files. See https://github.com/Andereoo/TkinterWeb/blob/main/tkinterweb/docs/FAQ.md for more information.

Error: Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Local\Temp\ONEFIL~2\tkinterweb\__init__.py", line 31, in <module tkinterweb>
ModuleNotFoundError: No module named 'bindings'


If you think this is a bug, please file a bug report at https://github.com/Andereoo/TkinterWeb.
```

**Comment by lalitdagre** [comment]
> conda-fo

I have tested with the latest version of Nuitka 1.3.7 but no success.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

It's not working for other OSes yet, due to the DLLs being there for each platform, but I do not want to include unused ones, more branches will be needed. But e.g. Linux 32 bit, I am not sure I even know anymore what it is supposed to output for arch, and for macOS we do not provide arch tags yet either, so more work will be needed.

Also, the problem you encountered is one of manually expanding `sys.path` with the package directory, which makes the modules visible at run time, but Nuitka doesn't know about it, unless `PYTHONPATH` is set. I added a new mechanism for plugins to be allowed to do that. So that error wasn't about DLLs or data files yet, it is just a dumb hack for what I assume is a strange API they intend to expose.

I am actually writing a post about this detailing the Yaml configuration now done for this package.

**Comment by lalitdagre** [comment]
Thanks for considering the issue. Well with the factory branch still no success, still getting below error

```
ModuleNotFoundError: The files required to run TkinterWeb could not be found. This usually occurs when bundling TkinterWeb into an app without forcing the application maker to include all nessessary files. See https://github.com/Andereoo/TkinterWeb/blob/main/tkinterweb/docs/FAQ.md for more information.

Error: Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Local\Temp\ONEFIL~3\tkinterweb\__init__.py", line 31, in <module tkinterweb>
ModuleNotFoundError: No module named 'bindings'


If you think this is a bug, please file a bug report at https://github.com/Andereoo/TkinterWeb.
```

However, the PYTHONPATH setting hack is working. Thanks for helping out,  but it will be great if it will work by specifying some switch in command it self.

**Comment by kayhayen** [comment]
I am not convinced you managed to successfully update Nuitka. This shows all symptoms of the Yaml configuration not being changed at all. You can now use develop, I made a pre-release with it.

**Comment by kayhayen** [comment]
This has been part of the 1.4 release, I think I forgot to close this issue.
