### ISSUE TITLE
compiled standalone with importlib and psutil

### ISSUE THREAD

**Issue by DukSon1224** [Nuitka/Nuitka#2075]
```
>python --version
Python 3.10.9

>python -m nuitka --version
1.4.8
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: d:\MyProjects\py\test\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\devFiles\vsBuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe (cl 14.3).

>python -m pip freeze
black==23.1.0
click==8.1.3
colorama==0.4.6
mypy-extensions==1.0.0
Nuitka==1.4.8
ordered-set==4.1.0
packaging==23.0
pathspec==0.11.0
platformdirs==3.0.0
psutil==5.9.4
tomli==2.0.1
zstandard==0.20.0
```

I found a weird thing about compiled standalone exe with `importlib` and `psutil`.
I wrote a short code to reproduce the thing.
```
from importlib import resources
import psutil


def getPath(filename: str, package: str = "resource") -> str:
    source = resources.files(package).joinpath(filename)
    print("source = ", source)
    print("type(source) = ", type(source))
    with resources.as_file(source) as f:
        return str(f.absolute())


if __name__ == "__main__":
    print(getPath("test.txt"))

```
and the follwing is the file tree:
```
workspaceFolder
├ resource
│  └ test.txt
└ test.py
```

and below is options to compile script:
```
nuitka ^
--standalone ^
--include-data-dir=resource=resource ^
--remove-output ^
--output-dir=bin ^
--output-filename=test.exe ^
test.py
```

and then the output is
```
>bin\test.dist\test.exe     
source =  D:\MyProjects\py\test\bin\test.dist\resource\\test.txt
type(source) =  <class 'nuitka_resource_reader_files'>
Traceback (most recent call last):
  File "D:\MyProjects\py\test\bin\test.dist\test.py", line 14, in <module>
  File "D:\MyProjects\py\test\bin\test.dist\test.py", line 10, in getPath
AttributeError: 'nuitka_resource_reader_files' object has no attribute 'absolute'
```

`psutil` did nothing just imported but it cause an error.
If I remove `import psutil`, then it works well without any problem.
I don't know why it happens..

Output without `import psutil` is
```
>bin\test.dist\test.exe
source =  D:\MyProjects\py\test\bin\test.dist\resource\test.txt
type(source) =  <class 'pathlib.WindowsPath'>
D:\MyProjects\py\test\bin\test.dist\resource\test.txt
```

And, in the first output, `print("source = ", source)` said `source =  D:\MyProjects\py\test\bin\test.dist\resource\\test.txt`.
It has a wrong path with doubled back-slash in the last joinning.

How can I use `importlib` and `psutil` properly..?

**Comment by kayhayen** [comment]
It seems we need to provide a method `absolute` for the our loader files object too. Should be easy enough. Should be in a hotfix 1.4.9 if there is any, but I have to yet create the code of course.

**Comment by DukSon1224** [comment]
The object returned by `resources.files` has a path with trailling backslash when compiled. Is it intended..? It causes double backslash when using `joinpath`.

**Comment by kayhayen** [comment]
@DukSon1224 of course it is, and always make sure to mention me, no matter how urgent or important things are, that way I have less time to waste on other issues

**Comment by kayhayen** [comment]
I was just checking, and `absolute` is really just one of way too many functions that the Python object exposes. There is basically the whole `os` module exposed in another form. I guess, I will be lazy and implement only what PyPI relevant packages pick up. Thanks for the reproducer, that is nice to work with.

**Comment by DukSon1224** [comment]
@kayhayen I'm sorry for taking your time. I was hasty in creating the issue without looking into it in detail. As you said, the implementation of `absolute` was not required. Thank you for your kind comment.

I fixed my code just using `os.path.abspath(str(f))`.

**Comment by kayhayen** [comment]
I never criticized your report, I think I said "hanks for the reproducer, that is nice to work with", However, it seems you missed my point, which is no surprise when using irony, successful communication becomes unlikely, but sometimes I cannot help myself.

**Comment by kayhayen** [comment]
This is part of the 1.5 release, there was no hotfix to put it into anymore.
