### ISSUE TITLE
standalone mode sets PYTHONHOME, breaks python modules

### ISSUE THREAD

**Issue by hermannch** [Nuitka/Nuitka#2168]
Hi,

compiled executable fails to invoke external python scripts , if `nuitka --standalone` is used. 

Affected versions:
* 1ee8c7a200d7034020df831695f63f1c467a9496 introduced the bug
* 4d9e915fb0182ad1d7537e6183424a7119a0cb82 (develop, as of now)

Unfortunately 1ee8c7a200d7034020df831695f63f1c467a9496 doesn't communicate which issue it tries to solve, so i couldn't come up with a solution other than reverting it.

### info

```
+ python -m nuitka --version
1.5rc2
Commercial: None
Python: 3.10.7 (main, Mar 10 2023, 10:47:39) [GCC 12.2.0]
Flavor: Debian Python
Executable: ../venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.10
Version C compiler: /usr/lib/ccache/gcc (gcc).
```

### SSCCE

```
#!/bin/sh

# subprocess'ing python modules fails due to wrong PYTHONHOME
# bisected commit: 1ee8c7a200d7034020df831695f63f1c467a9496

set -eux

cat <<REQUIREMENTS >requirements.txt
# first appeared with 1ee8c7a
# https://github.com/Nuitka/Nuitka/archive/1ee8c7a200d7034020df831695f63f1c467a9496.zip
https://github.com/Nuitka/Nuitka/archive/develop.zip
REQUIREMENTS

cat <<EXTERNAL_CMD >./external.py
#!/usr/bin/env python3

print("hi from external")
EXTERNAL_CMD

cat <<MWE >./mwe.py
#!/usr/bin/env python3

import shlex
import subprocess

subprocess.run(shlex.split("python3 --version"), check=True)
# this fails when built --standalone
subprocess.run(shlex.split("python3 ./external.py"), check=True)
MWE

rm -rf venv
python3 -m venv venv
. "venv"/bin/activate

pip install -r requirements.txt

python3 -m nuitka \
	--standalone \
	./mwe.py

echo
echo

# standalone mode fails
./mwe.dist/mwe.bin

# + ./mwe.dist/mwe.bin
# Python 3.10.7
# Python path configuration:
#   PYTHONHOME = './nuitka-subprocess-pythonhome-bug/mwe.dist'
#   PYTHONPATH = (not set)
#   program name = 'python3'
#   isolated = 0
#   environment = 1
#   user site = 1
#   import site = 1
#   sys._base_executable = './nuitka-subprocess-pythonhome-bug/venv/bin/python3'
#   sys.base_prefix = './nuitka-subprocess-pythonhome-bug/mwe.dist'
#   sys.base_exec_prefix = './nuitka-subprocess-pythonhome-bug/mwe.dist'
#   sys.platlibdir = 'lib'
#   sys.executable = './nuitka-subprocess-pythonhome-bug/venv/bin/python3'
#   sys.prefix = './nuitka-subprocess-pythonhome-bug/mwe.dist'
#   sys.exec_prefix = './nuitka-subprocess-pythonhome-bug/mwe.dist'
#   sys.path = [
#     './nuitka-subprocess-pythonhome-bug/mwe.dist/lib/python310.zip',
#     './nuitka-subprocess-pythonhome-bug/mwe.dist/lib/python3.10',
#     './nuitka-subprocess-pythonhome-bug/mwe.dist/lib/python3.10/lib-dynload',
#   ]
# Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
# Python runtime state: core initialized
# ModuleNotFoundError: No module named 'encodings'
# 
# Current thread 0x00007fc1da8da040 (most recent call first):
#   <no Python frame>
# Traceback (most recent call last):
#   File "./nuitka-subprocess-pythonhome-bug/mwe.dist/mwe.py", line 7, in <module>
#   File "./nuitka-subprocess-pythonhome-bug/mwe.dist/subprocess.py", line 524, in run
# subprocess.CalledProcessError: Command '['python3', './external.py']' returned non-zero exit status 1.
```

**Comment by kayhayen** [comment]
Thanks for the report. The intent is clearly for `PYTHONHOME` to be not set only during Nuitka's init phase, and to restore it later. Big thanks for doing the bisect, makes it easy for me.

**Comment by kayhayen** [comment]
Yes, `PYTHONHOME` is no longer restored to its old value, on no platform apparently. Given the effort the code did, to do it properly, that's a shame. The root cause is of course the loss of the reverting of these variables.

**Comment by kayhayen** [comment]
Turns out, this was by mistake, during development, I must have commented out things.

```
-    // undoEnvironmentVariable("PYTHONHOME", old_env_pythonhome);
+    undoEnvironmentVariable(makeEnvironmentLiteral("PYTHONHOME"), old_env_pythonhome);
```

That is the fix. I am likely going to rebase Nuitka, because this is going to break bisecting other things.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by hermannch** [comment]
current `factory` (10a5e89a0932672e681856f6b18dafeceeb8aa5c) doesn't fix it for me.

simplified SSCCE
``` sh
#!/bin/sh
set -eux

cat <<EXTERNAL_CMD >./external.py
#!/usr/bin/env python3.10
print("hi from external")
EXTERNAL_CMD
chmod +x ./external.py

cat <<MWE >./mwe.py
#!/usr/bin/env python3.10
import subprocess
subprocess.run("./external.py", check=True)
MWE

rm -rf ./venv
python3.10 -m venv ./venv
. ./venv/bin/activate
pip install --no-cache-dir https://github.com/Nuitka/Nuitka/archive/factory.zip

# standalone mode fails
python3.10 -m nuitka \
	--standalone \
	./mwe.py
./mwe.dist/mwe.bin
```

yields

```
...

Nuitka:INFO: Successfully created 'mwe.dist/mwe.bin'.
+ ./mwe.dist/mwe.bin
Traceback (most recent call last):
  File "/tmp/mwe.dist/subprocess.py", line 69, in <module>
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mwe.dist/mwe.py", line 2, in <module>
  File "/tmp/mwe.dist/subprocess.py", line 75, in <module>
ModuleNotFoundError: No module named 'select'
```

**Comment by kayhayen** [comment]
I don't think that is the `PYTHONHOME` regression. Since `venv` doesn't use environment variables really, I have to wonder, if the standalone binary itself, but I don't see anything when I execute this:

```
import os
os.system("env")
```

I am tempted to think that maybe `subprocess` is broken on factory, esp. as `msvcrt` sounds to Windows only. I need to try on Linux too I guess.

**Comment by kayhayen** [comment]
Yes, `subprocess` on non-Windows is broken unless something else pulls in the imports it needs. That's an optimization there for hello world size that bears the risk to break stdlib dependencies.

**Comment by kayhayen** [comment]
This subprocess thing is now fixed on develop as well, turns out it was already part of the last pre-release already.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.7 that I just made.

**Comment by hermannch** [comment]
fixed, thanks
