### ISSUE TITLE
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. No module named 'transformers.models.encoder_decoder.configuration_encoder_decoder'

### ISSUE THREAD

**Issue by JanWerder** [Nuitka/Nuitka#2193]
Hello,
I'm getting the following problem, when I run the compiled output of my project, which includes the transformers library.

```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\transformers\utils\import_utils.py", line 1146, in _get_module
  File "importlib.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers.models.encoder_decoder.configuration_encoder_decoder'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\transformers\utils\import_utils.py", line 1146, in _get_module
  File "importlib.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\transformers\models\auto\tokenization_auto.py", line 28, in <module transformers.models.auto.tokenization_auto>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\transformers\utils\import_utils.py", line 1136, in __getattr__
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\transformers\utils\import_utils.py", line 1151, in _get_module
RuntimeError: Failed to import transformers.models.encoder_decoder.configuration_encoder_decoder because of the following error (look up to see its traceback):
No module named 'transformers.models.encoder_decoder.configuration_encoder_decoder'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\app.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\open_clip\__init__.py", line 1, in <module open_clip>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\open_clip\coca_model.py", line 15, in <module open_clip.coca_model>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\open_clip\model.py", line 16, in <module open_clip.model>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\open_clip\hf_model.py", line 13, in <module open_clip.hf_model>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\transformers\utils\import_utils.py", line 1137, in __getattr__
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\transformers\utils\import_utils.py", line 1136, in __getattr__
  File "C:\Users\janwe\dev\SUPERS~2\clip\APP~1.DIS\transformers\utils\import_utils.py", line 1151, in _get_module
RuntimeError: Failed to import transformers.models.auto.tokenization_auto because of the following error (look up to see its traceback):
Failed to import transformers.models.encoder_decoder.configuration_encoder_decoder because of the following error (look up to see its traceback):
No module named 'transformers.models.encoder_decoder.configuration_encoder_decoder'
```

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```
1.5.6
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\janwe\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual 
Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe (cl 14.2).
```

* How did you install Nuitka and Python

Installed using pip

* The specific PyPI names and versions

  > python -m pip freeze

```
altgraph==0.17.3
asttokens==2.0.8
backcall==0.2.0
bark==0.1.0
certifi==2022.12.7
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
debugpy==1.6.3
decorator==5.1.1
entrypoints==0.4
executing==1.1.1
filelock==3.12.0
Flask==2.2.3
ftfy==6.1.1
huggingface-hub==0.13.4
idna==3.4
ipykernel==6.16.0
itsdangerous==2.1.2
jedi==0.18.1
Jinja2==3.1.2
jupyter-core==4.11.1
jupyter_client==7.3.5
MarkupSafe==2.1.2
matplotlib-inline==0.1.6
mpmath==1.3.0
nest-asyncio==1.5.6
netaddr==0.8.0
networkx==3.1
Nuitka==1.5.6
numpy==1.24.3
open-clip-torch==2.17.1
ordered-set==4.1.0
packaging==23.1
parso==0.8.3
pefile==2023.2.7
pickleshare==0.7.5
Pillow==9.5.0
prompt-toolkit==3.0.31
protobuf==3.20.3
psutil==5.9.2
pure-eval==0.2.2
pyinstaller==5.10.1
pyinstaller-hooks-contrib==2023.2
python-dateutil==2.8.2
pywin32==304
pywin32-ctypes==0.2.0
PyYAML==6.0
pyzmq==24.0.1
regex==2023.3.23
requests==2.28.2
sentencepiece==0.1.98
six==1.16.0
stack-data==0.5.1
sympy==1.11.1
timm==0.6.13
tokenizers==0.13.3
torch==2.0.0+cu117
torchvision==0.15.1+cu117
tornado==6.2
tqdm==4.65.0
traitlets==5.4.0
transformers==4.28.1
typing_extensions==4.5.0
urllib3==1.26.15
waitress==2.1.2
wcwidth==0.2.5
WebOb==1.8.7
Werkzeug==2.2.3
zstandard==0.21.0
```

I think https://github.com/Nuitka/Nuitka/issues/2151 is similar, but doesn't match 100%, so I'm opening this issue as well.

**Comment by ArEnSc** [comment]
Got the same issue, also building is a nightmare since it takes like 2-3 hours

**Comment by ArEnSc** [comment]
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\transformers\utils\import_utils.py", line 1146, in _get_module
  File "importlib.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers.models.encoder_decoder.configuration_encoder_decoder'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\transformers\utils\import_utils.py", line 1146, in _get_module
  File "importlib.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\transformers\models\auto\tokenization_auto.py", line 28, in <module transformers.models.auto.tokenization_auto>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\transformers\utils\import_utils.py", line 1136, in __getattr__
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\transformers\utils\import_utils.py", line 1151, in _get_module
RuntimeError: Failed to import transformers.models.encoder_decoder.configuration_encoder_decoder because of the following error (look up to see its traceback):
No module named 'transformers.models.encoder_decoder.configuration_encoder_decoder'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\transformers\utils\import_utils.py", line 1137, in __getattr__
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\transformers\utils\import_utils.py", line 1136, in __getattr__
  File "C:\Users\Tensor\Desktop\aiengine\GPTQ-F~1\MAIN~1.DIS\transformers\utils\import_utils.py", line 1151, in _get_module
RuntimeError: Failed to import transformers.models.auto.tokenization_auto because of the following error (look up to see its traceback):
Failed to import transformers.models.encoder_decoder.configuration_encoder_decoder because of the following error (look up to see its traceback):
No module named 'transformers.models.encoder_decoder.configuration_encoder_decoder'

**Comment by ArEnSc** [comment]
Ok so basically, I was in the discord and more or less this has to do with pytorch v2.0 step it down 1 version, the v2.0 pytorch isn't ready

**Comment by Weinwurm** [comment]
I have the same problem with pytorch 1.12.0+cu113

**Comment by ArEnSc** [comment]
> I have the same problem with pytorch 1.12.0+cu113

damn I am wondering then if this has to do with the version of nuitka I am trying this with 1.13 now

**Comment by ArEnSc** [comment]
Ok this might have to do with transformers

**Comment by ArEnSc** [comment]
yeah I verified this isnt a pytorch problem it's transformers, pytorch 2.0 works just fine when compiled

**Comment by kayhayen** [comment]
I am not happy with the pytorch 2.0 anti-bloat situation, it pulls in too many things, but good to heat it works generally, because I will be busy with another issue for 1.x for some time

**Comment by kayhayen** [comment]
So, this is the code that prevents e.g. torch from being found. I think people here want it to find torch foremost.

```
_torch_version = "N/A"
if USE_TORCH in ENV_VARS_TRUE_AND_AUTO_VALUES and USE_TF not in ENV_VARS_TRUE_VALUES:
    _torch_available = importlib.util.find_spec("torch") is not None
    if _torch_available:
        try:
            _torch_version = importlib_metadata.version("torch")
            logger.info(f"PyTorch version {_torch_version} available.")
        except importlib_metadata.PackageNotFoundError:
            _torch_available = False
```

The environment variables `USE_TORCH` and `USE_FLAX` should probably not be runtime dependent. They have good defaults, but I assume, we will want to preserve their current values from during compilation. Or is there a case to be made, to decide on the target machine, I doubt so. Same goes for `FORCE_TF_AVAILABLE`. I am taking note of these. Once we specialize `os.environ` these will become freezable as well.

What is holding us back here, is this:

```
from .versions import importlib_metadata
```

The `find_spec` and the `version` calls would otherwise work. In the spirit of anti-bloat, the above code block could be moved to compile time, such that on the target machines, it wouldn't have to check versions. The other solution would be to recognize the hard import of `importlib.metadata` from `transforms.utils.versions` there and then just automatically work.

This kind of cross module optimization is not yet done in Nuitka, but very much ought to, and these hard modules might be a good place to start. However in the mean time I am experimenting with the low hanging fruit solution. I think replacing `from .versions import importlib_metadata` with `import importlib.metadata as importlib_metadata`with the current anti-bloat will cut it for now.

I shall try that now. I believe there may also be implicit dependencies. I am missing example programs here. If you have a small one that will be nice. For now the top level import fails. I believe it cannot always have done that, since I think I did anti-bloat of transformers before, but I guess it's a package evolving quickly.

**Comment by kayhayen** [comment]
Ah, speaking of that, for an older version, this was working:

```
- module-name: 'transformers.utils.versions'
  anti-bloat:
    - description: 'disable runtime metadata check for core dependencies'
      change_function:
        # TODO: Forcing inline of this will be better solution.
        'require_version_core': "'(lambda requirement: None)'"
```

**Comment by JanWerder** [comment]
I hope I can help with this minimal example:

```
import torch
from PIL import Image
import open_clip

print("Loading model")

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

model, _, transform = open_clip.create_model_and_transforms(
    model_name="coca_ViT-L-14", pretrained="mscoco_finetuned_laion2B-s13B-b90k"
)

with torch.no_grad(), torch.cuda.amp.autocast():
    start = time.time() 
    # Generate a random image for performance measurement
    im = torch.randn(1, 3, 224, 224)
    im = transform(im).unsqueeze(0)
    generated = model.generate(im)
    end = time.time()
    performanceSample = end - start
```

used with the command `python -m nuitka --follow-imports --standalone .\app-demo.py`

Just to make sure, there is no easy way to fix that for as end-users, right @kayhayen?

**Comment by kayhayen** [comment]
So, I got that anti-bloat stuff done, but I got an extracted script (from `transformers.utils.import_lib`) now, with two calls of `importlib_metadata.version("torch")` and it appears, the first call gives correct version, and the second does not. I tried to remove some innocent code in between, but it appears that something breaks the hard import propagation of `importlib_metadata` there, and I have yet to discover what it is exactly. As you can probably guess, iterations will take a while to narrow this done, since I have to do `import pytorch` for things to work.

That would be a kind of "bug" I suppose. I am very interested, what construct is causing this.

**Comment by kayhayen** [comment]
So, it seems the loop tracing does not conclude with a trace that allows even "very trusted" values to go through, so the hard import resolution fails the second time, because for TensorFlow, names are checked in a loop, causing later lookups to all fail. 

This is an omission that I should be able to add, but this pushes it absolutely into 1.6 territory as that's an invasive fix, but that's right around the corner anyway.

**Comment by kayhayen** [comment]
It seems doing  that for the loop, is something doable, however, for the time being I consider it a risky change, that I do not want to go into right now. Therefore, instead, I will just use anti-bloat to remove the attempt to scan for tensorflow, and then it should probably just work for pytorch at least. Tensorflow won't do scan properly until we have the loop in there unrolled, which is even further away.

**Comment by kayhayen** [comment]
So, I figured out how to do it properly, and now it only gives me import errors. The lazy importing seems to be also hiding the modules somehow, so a simple `transformers.pipeline` import is giving me an `ImportError` that is not justified. Need to dig deep there.

**Comment by kayhayen** [comment]
Ok, on factory there is a new plugin `transformers`, that is always on, and gets this fixed such that non-trivial programs also work. I am now stabilizing factory before including this in a release.

**Comment by kayhayen** [comment]
So, I did anti-bloat for the transformers, and now tried with newer pytorch, and had a `RecursionError` with sympy now, that I need to look into, that's very ugly.

**Comment by kayhayen** [comment]
This is part of the stable release 1.6 that I just made. The recursion error was fixed too, so it should be good now.

**Comment by JanWerder** [comment]
Hey,
Thanks for all the work so far. I'm sadly still getting an compilation error.
My log attached below.

```
PS C:\Users\janwe\dev\clip> python -m nuitka --follow-imports app.py
Nuitka-Options:INFO: Used command line options: --follow-imports app.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.6' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'unittest' in 'torch._dynamo.config_utils' (at
Nuitka-Plugins:WARNING: 'C:\Python311\Lib\site-packages\torch\_dynamo\config_utils.py:7') encountered. It may slow down
Nuitka-Plugins:WARNING: compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'unittest' in 'torch._dynamo.config_utils' (at
Nuitka-Plugins:WARNING: 'C:\Python311\Lib\site-packages\torch\_dynamo\config_utils.py:7') encountered. It may slow down
Nuitka-Plugins:WARNING: compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'doctest' in 'sympy.testing.runtests' (at
Nuitka-Plugins:WARNING: 'C:\Python311\Lib\site-packages\sympy\testing\runtests.py:26') encountered. It may slow down
Nuitka-Plugins:WARNING: compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka-Inclusion:INFO: Cannot find distribution 'jax' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:107', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'flax' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:108', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'datasets' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:120', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'datasets' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:121', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'detectron2' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:130', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'faiss' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:138', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'faiss-cpu' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:142', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'ftfy' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:150', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'coloredlogs' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:158', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'tf2onnx' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:174', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'pytorch_quantization' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:190', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'soundfile' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:198', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'tensorflow_probability' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:206', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'timm' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:214', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'natten' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:222', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'phonemizer' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:238', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'pyctcdecode' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:246', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'librosa' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:254', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'oneccl_bind_pt' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:265', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'decord' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:272', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'jieba' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:279', expect potential run time problem, unless this is unused code.
Nuitka-Inclusion:INFO: Cannot find distribution 'intel_extension_for_pytorch' at 'C:\Python311\Lib\site-packages\transformers\utils\import_utils.py:532', expect potential run time problem, unless this is unused code.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'setuptools' in 'torch.utils.cpp_extension' (at
Nuitka-Plugins:WARNING: 'C:\Python311\Lib\site-packages\torch\utils\cpp_extension.py:8') encountered. It may slow down
Nuitka-Plugins:WARNING: compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'setuptools' in 'torch.utils.cpp_extension' (at
Nuitka-Plugins:WARNING: 'C:\Python311\Lib\site-packages\torch\utils\cpp_extension.py:24') encountered. It may slow down
Nuitka-Plugins:WARNING: compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'setuptools' in 'torch.utils.cpp_extension' (at
Nuitka-Plugins:WARNING: 'C:\Python311\Lib\site-packages\torch\utils\cpp_extension.py:24') encountered. It may slow down
Nuitka-Plugins:WARNING: compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
Nuitka-Inclusion:INFO: Cannot find distribution 'wheel' at 'C:\Python311\Lib\site-packages\setuptools\installer.py:34', expect potential run time problem, unless this is unused code.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.2).
Nuitka-Scons:INFO: Backend linking program with 4255 files (no progress information available for this stage).
Unexpected output from this command:
<clcache> /Fostatic_src\CompiledFunctionType.obj /c "static_src\CompiledFunctionType.cpp" /TP /nologo /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\Python311\include /I. /IC:\PYTHON~2\Lib\SITE-P~1\NUITKA~1.EGG\nuitka\build\include /IC:\PYTHON~2\Lib\SITE-P~1\NUITKA~1.EGG\nuitka\build\static_src
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(378): error C2143: Syntaxfehler: Es fehlt "]" vor "Konstante"
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(378): error C3260: "Konstante": Unerwartete Token vor Text der Lambdafunktion werden \x81bersprungen.
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(564): error C2065: "gen": nichtdeklarierter Bezeichner
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(565): error C2065: "gen": nichtdeklarierter Bezeichner
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(567): error C2065: "gen": nichtdeklarierter Bezeichner
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(582): error C3487: "PyObject *": Alle R\x81ckgabeausdr\x81cke m\x81ssen in denselben Typ hergeleitet werden: Zuvor war es "int".
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(582): error C2440: "return": "PyObject *" kann nicht in "int" konvertiert werden
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(582): note: Es gibt keinen Kontext, in dem diese Konvertierung m\x94glich ist
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(586): error C2062: "_frame"-Typ unerwartet
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(586): error C2143: Syntaxfehler: Es fehlt ";" vor "{"
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(586): error C2447: "{": Funktionsheader fehlt - Parameterliste im alten Stil?
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(614): error C3861: "_Nuitka_PyFrame_New_NoTrack": Bezeichner wurde nicht gefunden.
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(865): error C3861: "Nuitka_PyGen_yf": Bezeichner wurde nicht gefunden.
C:\Python311\Lib\site-packages\Nuitka-1.6-py3.11-win-amd64.egg\nuitka\build\static_src\CompiledGeneratorTypeUncompiledIntegration.c(1484): error C3861: "Nuitka_PyGen_yf": Bezeichner wurde nicht gefunden.
scons: *** [static_src\CompiledFunctionType.obj] Error 2
```

**Comment by kayhayen** [comment]
@JanWerder new issues posting below closed issues is a surefire way to get ignored, open a new issue

**Comment by kayhayen** [comment]
@JanWerder posting below closed issues is a surefire way to get ignored, make a new report for your issue
