### ISSUE TITLE
PySide6: Widget Connections crashing exe

### ISSUE THREAD

**Issue by pHiney** [Nuitka/Nuitka#2449]
- Please check out if the develop version of Nuitka works better for you.
Why, how different is it likely to be to 1.8.2 ?

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
(.venv) C:\git\PathOfBuilding-Python>python -m nuitka --version
1.8.2
Commercial: None
Python: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\git\PathOfBuilding-Python\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).

- How did you install Nuitka and Python
python-3.11.5-amd64.exe, full install for everyone, including adding to PATH
poetry install
poetry shell
pip install Nuitka

- The specific PyPI names and versions
(.venv) C:\git\PathOfBuilding-Python>python -m pip freeze
astroid==2.15.6
attrs==23.1.0
black==22.12.0
build==0.10.0
CacheControl==0.13.1
certifi==2023.7.22
charset-normalizer==3.2.0
cleo==2.0.1
click==8.1.7
colorama==0.4.6
crashtest==0.4.1
dill==0.3.7
distlib==0.3.7
dulwich==0.21.6
filelock==3.12.4
idna==3.4
importlib-metadata==6.8.0
installer==0.7.0
isort==5.12.0
jaraco.classes==3.3.0
jsonschema==4.17.3
keyring==24.2.0
lazy-object-proxy==1.9.0
luadata==1.0.5
mccabe==0.7.0
more-itertools==10.1.0
msgpack==1.0.5
mypy-extensions==1.0.0
Nuitka==1.8.2
numpy==1.26.0
ordered-set==4.1.0
packaging==23.1
pathspec==0.11.2
pexpect==4.8.0
pkginfo==1.9.6
platformdirs==3.10.0
poetry==1.6.1
poetry-core==1.7.0
poetry-plugin-export==1.5.0
psutil==5.9.5
ptyprocess==0.7.0
pylint==2.17.5
pyperclip==1.8.2
pyproject_hooks==1.0.0
PyQt6==6.5.2
PyQt6-Qt6==6.5.2
PyQt6-sip==13.5.2
pyrsistent==0.19.3
PySide6==6.5.2
PySide6-Addons==6.5.2
PySide6-Essentials==6.5.2
pywin32-ctypes==0.2.2
rapidfuzz==3.3.0
requests==2.31.0
requests-toolbelt==1.0.0
rpds-py==0.10.3
shellingham==1.5.3
shiboken6==6.5.2
six==1.16.0
SLPP==1.2.3
tomlkit==0.12.1
trove-classifiers==2023.8.7
urllib3==2.0.4
virtualenv==20.24.5
wrapt==1.15.0
xmltodict==0.13.0
zipp==3.16.2
zstandard==0.21.0

- Many times when you get an error from Nuitka, your setup may be special

Executable is created, simple MRE may not assist here

- Also supply a Short, Self Contained, Correct, Example

A simple MRE may not assist here. I'm not sure how I could go about that, given it's part of a project.
I do understand you'd like it simple, but I can't see how

I don't expect you to compile it, just want you to see how things are used.
https://github.com/pHiney/PathOfBuilding-Python

- Provide in your issue the Nuitka options used
```
# nuitka-project: --onefile
# nuitka-project: --standalone
# nuitka-project: --onefile-windows-splash-screen-image=Assets/PathOfBuilding.png
# nuitka-project: --enable-plugin=pyside6
# nuitka-project: --include-data-dir=src/data=data
# nuitka-project: --windows-icon-from-ico=Assets/Icons/PathOfBuilding.ico
# nuitka-project: --onefile-tempdir-spec="%TEMP%/PoB_%PID%"
# nuitka-project: --onefile-no-compression
# nuitka-project: --include-plugin-directory=src/dialogs
# nuitka-project: --clean-cache=all
```

- Note if this is a regression
No Idea.

- Consider getting commercial support
No. This is an open source project

- Actual Issue
When run as an executable on Windows, opening the Open File dialog (Ctrl-O) cause the executable to crash and exit with no message. Running the program using "python PathOfBuilding.py" does not crash.

The offending lines are (line 81-84 browse_file_dialog.py
```python
        self.list_Files.itemClicked.connect(self.list_file_clicked)
        self.list_Files.itemDoubleClicked.connect(self.list_file_double_clicked)
        self.lineEdit_CurrDir.textChanged.connect(self.lineedit_currdir_changed)
        self.lineEdit_CurrDir.editingFinished.connect(self.lineedit_currdir_editing_finished)
```
It doesn't matter which ones are present or commented out. They all cause the crash.
If the four lines are commented out, no crash but not much functionality either.

Output when run from executable. Note the PySide6 and connect errors.
```
(.venv) c:\_complete\_new>PathOfBuilding.exe
2023-09-20 22:23:47.621989. Path of Building, running on Windows 10; 10.0.22621
Loading Tree: 3.22
2023-09-20 22:23:49.433824: ('add_tree_images, full_clear=True',) : File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\widgets\tree_view.py", line 335, in add_tree_images
QGraphicsScene::addItem: cannot add null item
2023-09-20 22:23:49.583788: ('add_tree_images, full_clear=False',) : File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\widgets\tree_view.py", line 335, in add_tree_images
QGraphicsScene::removeItem: cannot remove 0-item
QGraphicsScene::addItem: cannot add null item
2023-09-20 22:23:49.588323: ('add_tree_images, full_clear=False',) : File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\widgets\tree_view.py", line 335, in add_tree_images
QGraphicsScene::removeItem: cannot remove 0-item
QGraphicsScene::addItem: cannot add null item
Traceback (most recent call last):
  File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\widgets\skills_ui.py", line 717, in change_socket_group
  File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\widgets\skills_ui.py", line 760, in load_socket_group
  File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\widgets\skills_ui.py", line 333, in connect_skill_triggers
  File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\PySide6\QtCore-postLoad.py", line 12, in patched_connect
TypeError: 'PySide6.QtCore.QObject.connect' called with wrong argument types:
  PySide6.QtCore.QObject.connect(ListBox, str, compiled_frame, ConnectionType)
Supported signatures:
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, Callable, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(bytes, Callable, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(bytes, PySide6.QtCore.QObject, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, PySide6.QtCore.QMetaMethod, PySide6.QtCore.QObject, PySide6.QtCore.QMetaMethod, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, PySide6.QtCore.QObject, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
2023-09-20 22:23:49.676071: ('add_tree_images, full_clear=True',) : File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\widgets\tree_view.py", line 335, in add_tree_images
QGraphicsScene::addItem: cannot add null item
```

Output from running as python from the command line. Not all the QGraphicsScene still exist (still to be solved) so not relevant. The pyside and connect errors are not present.
```
(.venv) C:\git\PathOfBuilding-Python\src>python PathOfBuilding.py
2023-09-20 22:30:53.456320. Path of Building, running on Windows 10; 10.0.22621
Loading Tree: 3.22
2023-09-20 22:30:55.048993: ('add_tree_images, full_clear=True',) : File "C:\git\PathOfBuilding-Python\src\widgets\tree_view.py", line 335, in add_tree_images
QGraphicsScene::addItem: cannot add null item
2023-09-20 22:30:55.266608: ('add_tree_images, full_clear=False',) : File "C:\git\PathOfBuilding-Python\src\widgets\tree_view.py", line 335, in add_tree_images
QGraphicsScene::removeItem: cannot remove 0-item
QGraphicsScene::addItem: cannot add null item
2023-09-20 22:30:55.268128: ('add_tree_images, full_clear=False',) : File "C:\git\PathOfBuilding-Python\src\widgets\tree_view.py", line 335, in add_tree_images
QGraphicsScene::removeItem: cannot remove 0-item
QGraphicsScene::addItem: cannot add null item
2023-09-20 22:30:55.321534: ('add_tree_images, full_clear=True',) : File "C:\git\PathOfBuilding-Python\src\widgets\tree_view.py", line 335, in add_tree_images
QGraphicsScene::addItem: cannot add null item
```

Thanks in Advance
pH

**Comment by kayhayen** [comment]
Without a reproducer, that is largely useless to me even though you provide good information. 

Also I noticed this one:

```
Traceback (most recent call last):
  File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\widgets\skills_ui.py", line 717, in change_socket_group
  File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\widgets\skills_ui.py", line 760, in load_socket_group
  File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\widgets\skills_ui.py", line 333, in connect_skill_triggers
  File "C:\Users\Peter\AppData\Local\Temp\POB_21~1\PySide6\QtCore-postLoad.py", line 12, in patched_connect
TypeError: 'PySide6.QtCore.QObject.connect' called with wrong argument types:
  PySide6.QtCore.QObject.connect(ListBox, str, compiled_frame, ConnectionType)
```

So, if you could distill that out, it would be super helpful. It seems to me, as if we are making wrong assumptions
about the signatures to accept. You can of course edit this in Nuitka yaml config:

```
- module-name: 'PySide6.QtCore'
  implicit-imports:
    - depends:
        - 'PySide6.support.deprecated'
    - post-import-code:
        - |
          def patched_connect(self, receiver, type=None):
              type = type or QtCore.Qt.ConnectionType.AutoConnection
              if hasattr(receiver, "im_func"):
                  if hasattr(receiver.im_func, "__compiled__"):
                      patched_connect._protected = getattr(patched_connect, "_protected", set())
                      patched_connect._protected.add(receiver)

                  if not receiver.im_func.__name__.startswith("_pyside6_workaround_"):
                      receiver.im_func.__name__ = "_nuitka_" + receiver.im_func.__name__

              return orig_connect(self, receiver, type)

          from PySide6 import QtCore
          orig_connect = QtCore.SignalInstance.connect
          QtCore.SignalInstance.connect = patched_connect
```

Your call may not have the 3 argument form in that place. Something may more clever might be required to allow PySide to correctly dispatch here.

I think I started out assuming that only 1 argument is given, and then type became an optional one. I think we might have to use `*args, **kwargs` (are keyargs even OK, maybe not) and then resolve this in a minimal call that matches the original signature closer, adding the `type` if not given may also be just a bad idea.

**Comment by pHiney** [comment]
Sorry. I forgot to ask. Are the options ok ?
And I'll look at the yml and see what I can work out. ty

**Comment by pHiney** [comment]
Given adding these two lines to the yaml
```python
          def patched_connect(self, receiver, type=auto):
              saved_args = locals()
              print("saved_args1 is", saved_args)
```

I see that a working connect is 
```saved_args1 is {'self': <PySide6.QtCore.SignalInstance textChanged(QString) at 0x000001D751FD8E10>, 'receiver': <bound compiled_method SkillsUI.save_socket_group_settings of <widgets.skills_ui.SkillsUI object at 0x000001D763EF6C90>>, 'type': None}```
and a non working one is 
```saved_args1 is {'self': <PySide6.QtCore.SignalInstance currentRowChanged(int) at 0x000001D751FBFE90>, 'receiver': <compiled_frame at 0x000001D751F8BE40, file 'C:\\Users\\Peter\\AppData\\Local\\Temp\\POB_19~1\\widgets\\gem_ui.py', line 274, code fill_gem_list>, 'type': None}```

Have you run into compiled_frame before ?
Googling it hasn't yielded much.

**Comment by kayhayen** [comment]
Yes, but why a frame object would be the recceiver is an interesting question. Something in `widgets\\gem_ui.py', line 274, code fill_gem_list>` must lead up to that. You can also make inspect print call stacks no problem, to get a precise line, or assert against `inspect.isframe()` on that object. I wonder if that's a normal thing, which then uses one of the other signatures. However, not sure what it would mean to provide a frame.

**Comment by pHiney** [comment]
Ok, let's really open ours eyes. I inserted a print(type()) statement, and it revealed this.
```type(self.change_socket_group) <class 'compiled_frame'>```

But if we look more carefully, the error is against a totally different function. fill_gem_list() is not called from change_socket_group(). Is there a list mismatch going on inside Nuitka code ?
```
locals {'self': <PySide6.QtCore.SignalInstance currentRowChanged(int) at 0x00000208C29BFFD0>, '_receiver': <compiled_frame at 0x00000208C298BE40, file 'C:\\Users\\Peter\\AppData\\Local\\Temp\\POB_19~1\\widgets\\gem_ui.py', line 262, code fill_gem_list>, '_type': <ConnectionType.AutoConnection: 0>}
Traceback (most recent call last):
  File "C:\Users\Peter\AppData\Local\Temp\POB_19~1\widgets\skills_ui.py", line 718, in change_socket_group
  File "C:\Users\Peter\AppData\Local\Temp\POB_19~1\widgets\skills_ui.py", line 761, in load_socket_group
  File "C:\Users\Peter\AppData\Local\Temp\POB_19~1\widgets\skills_ui.py", line 334, in connect_skill_triggers
  File "C:\Users\Peter\AppData\Local\Temp\POB_19~1\PySide6\QtCore-postLoad.py", line 18, in patched_connect
```


so i updated connect triggers function to show me the type of all the triggered functions
```python
    def connect_skill_triggers(self):
        """re-connect triggers"""
        # print("connect_skill_triggers", self.triggers_connected)
        if self.triggers_connected:
            return  # Don't re-connect
        self.triggers_connected = True
        print("type(self.save_socket_group_settings)", type(self.save_socket_group_settings))
        self.win.check_SocketGroupEnabled.stateChanged.connect(self.save_socket_group_settings)
        self.win.check_SocketGroup_FullDPS.stateChanged.connect(self.save_socket_group_settings)
        self.win.combo_SocketedIn.currentIndexChanged.connect(self.save_socket_group_settings)
        self.win.lineedit_SkillLabel.textChanged.connect(self.save_socket_group_settings)
        print("type(self.change_skill_set)", type(self.change_skill_set))
        self.win.combo_SkillSet.currentIndexChanged.connect(self.change_skill_set)
        print("type(self.change_socket_group)", type(self.change_socket_group))
        self.win.list_SocketGroups.currentRowChanged.connect(self.change_socket_group)
```

this returned
type(self.change_socket_group) <class 'compiled_method'>
type(self.combo_gem_list_changed) <class 'compiled_method'>
type(self.change_skill_set) <class 'compiled_method'>
type(self.change_socket_group) <class 'compiled_frame'>

I don't see what is different about this.
```python
    @Slot()
    def change_socket_group(self, _new_group):
        """
        This triggers when the user changes an entry on the list of skills.

        :param _new_group: int: row number.
               -1 will occur during a combobox clear
        :return: N/A
        """
        print("change_socket_group", _new_group)
        # Clean up and save objects. If _index = -1, then this is the only thing emptying these widgets
        # these routines have the connect and disconnect routines
        if index_exists(self.xml_current_skill_set, _new_group):
            self.clear_socket_group_settings()
            self.load_socket_group(_new_group)
```

Just for stamps this is not a compiled_frame
type(self.combo_gem_list_changed) <class 'compiled_method'>

**Comment by pHiney** [comment]
When I run the program in pyCharm I get
type(self.save_socket_group_settings) <class 'method'>
type(self.change_skill_set) <class 'method'>
type(self.change_socket_group) <class 'method'>
type(self.save_socket_group_settings) <class 'method'>
type(self.change_skill_set) <class 'method'>
type(self.change_socket_group) <class 'method'>

and the same for 'python PathOfBuilding.py'

So I feel there is a code error in Nuitka.

thanks for your time
pH

**Comment by pHiney** [comment]
I moved the import to the top of the stanza to make things a bit cleaner if you like ...

```python
          from PySide6 import QtCore
          def patched_connect(self, _receiver, _type=QtCore.Qt.ConnectionType.AutoConnection):
```

**Comment by kayhayen** [comment]
So, I believe we are seeing corruption here. The very issue that the connect patch is trying to avoid, might be happening elsewhere as well. The memory of a method could be used by a frame later one. Nuitka keeps functions, frames in a free list, and does not release it. However, it may still happen if the refcount is dropped to zero by other code.

I will have a version of Nuitka where we have a toggle to disable it and then we should be able to assert it. PySide6 does release objects it should not. And before the patched connect code, that was a not a crasher in some cases, but sometimes leading to function objects being confused.

I will be busy with other stuff likely today, but I will add the feature for factory branch as soon as possible.

**Comment by kayhayen** [comment]
Please try develop with the option `--experimental=disable-freelist-all` and `--debug` and it should give an assertion I believe.

**Comment by pHiney** [comment]
I added those switches.
What do i do with this ?
```
PathOfBuilding.exe
2023-09-30 21:46:30.437550. Path of Building, running on Windows 10; 10.0.22621
Loading Tree: 3.22
Assertion failed: tmp_match_statement_1__indicator != NUITKA_BOOL_UNASSIGNED, file module.widgets.item_slot_ui.c, line 500
```

**Comment by kayhayen** [comment]
So, we seem to encounter a bug in `match`. You can look at the C file, find a line number set in some sort of exception error, and then extract a reproducer from there. Is `widgets` your code?

**Comment by pHiney** [comment]
widgets is a directory. so widgets\item_slot_ui.py

There are two match stanzas in that module. I'll try commenting them out and see if it makes a difference and/or moves on to another match statement.

**Comment by pHiney** [comment]
It moved on to another module.
Assertion failed: tmp_match_statement_2__indicator != NUITKA_BOOL_UNASSIGNED, file module.PoB.item.c, line 43611

**Comment by pHiney** [comment]
MRE for match

`Assertion failed: tmp_match_statement_1__indicator != NUITKA_BOOL_UNASSIGNED, file module.__main__.c, line 6044
`
```python
# nuitka-project: --standalone
# nuitka-project: --onefile
# nuitka-project: --onefile-windows-splash-screen-image=Assets/PathOfBuilding.png
# nuitka-project: --enable-plugin=pyside6
# nuitka-project: --include-data-dir=src/data=data
# nuitka-project: --windows-icon-from-ico=Assets/Icons/PathOfBuilding.ico
# nuitka-project: --onefile-tempdir-spec="%TEMP%/PoB_%PID%"
# nuitka-project: --onefile-no-compression
# nuitka-project: --include-plugin-directory=src/dialogs
# nuitka -project: --python-flag=static_hashes
# nuitka -project: --quiet
# nuitka-project: --clean-cache=all
# nuitka-project: --debug
# nuitka-project: --experimental=disable-freelist-all

title = "fred"
match title:
	case "Weapon 1 Swap":
		title = "Alt Weapon 1"
	case "Weapon 2 Swap":
		title = "Alt Weapon 2"

print(f"{title=}")

```

**Comment by kayhayen** [comment]
This with a space in there will be ignored, but looks pretty good to me. The reproducer is shockingly simple. My guess is that matching string literals produces something random. Not freelist related at all maybe, I only need `--debug` as an option.

**Comment by pHiney** [comment]
"Not freelist related at all maybe,"

I wonder if this just a bug stopping us from getting to the freelist issue.

Can you add to the 'C' code a comment with what python line this C code is representing, maybe just with the --debug option active. not sure.

ty

**Comment by kayhayen** [comment]
I will solve the first find first, but it's definitely real, and could cause corruption, which then could hit the freelist business, but I am not good at speculating, I will just see if it changes things. It's not a false alarm for sure.

There is `--trace` which makes run time unbearable, but adds per statement a line. I agree a more lightweight version that would do it for maybe even expressions, would be nice. I usually get away with finding a close exception raise.

I trimmed it to 
```
# nuitka-project: --debug

def f():
    title = "fred"
    match title:
        case "Weapon 1 Swap":
            title = "Alt Weapon 1"
        case "Weapon 2 Swap":
            title = "Alt Weapon 2"

    return title

print(f())
```

I was expecting to see some static optimization for this, and maybe it's done wrong, an indicator variable becomes unassigned, but remains used, maybe multiple propagations hinder one another or something like that. This of course should have become just `return fred` but it doesn't which is strange. Checking the `match` re-formulation for this right now, but I doubt it can be to blame of that.

**Comment by kayhayen** [comment]
Well, actually it is to blame, the indicator variable is never assigned to false, but checked against it indeed. Now I really wonder how this ever worked, but it seems the comparison goes for `tmp_match_statement_1__indicator == NUITKA_BOOL_TRUE` and `NUITKA_BOOL_UNASSIGNED` is without debug mode equivalent to `False` making it forgive to lack of assignment. 

So now I am adding that assignment, which should make it better for optimization, and avoids the assertion, but I don't think it can have any runtime impact. The assignment to NUITKA_BOOL_UNASSIGNED will now just be optimized away and be replaced with the assignment to `NUITKA_BOOL_FALSE` which is slightly better.

I will put this on factory, so you can retry with the original program please, this wasn't quite it.

**Comment by David-Worboys** [comment]
A bit late to this but I will say I noticed connects causing corruption and crashes in Nuitka compiles  back in Pyside 6.5.1 when I put this in my code -  widget_signal.connect(functools.partial(self._event_handler, event)) . instead of lambdas  It is not a 100% fix but more like 99%. I still get occasional corruption/lockup but usually near app start up. I was never able to get a minimal reproducer to report. I use Linux and Python 3.11

    def _install_event(
        self, event: Sys_Events, signal: str, use_lambda: bool = False
    ) -> None:
        """Installs the event handler for the given event on the widget.

        Note: Pyside6 6.5.1 broke lambda connects - TODO test later releases

        Args:
            event (Sys_Events): Event to install
            signal (str): Signal to connect the event handler to
            use_lambda (bool): True use lambda , False use functools.partial.
        """

        try:
            widget_signal: qtC.SignalInstance = getattr(self._widget, signal)

            try:
                widget_signal.disconnect()
            except TypeError:
                pass
            except RuntimeError:
                pass
            except ValueError:
                pass

            
            if use_lambda: # Pyside 6.5.1 will break with Lambda
                widget_signal.connect(lambda *args: self._event_handler(event, args))
            else:
                widget_signal.connect(functools.partial(self._event_handler, event))
        except AttributeError:
            pass

**Comment by pHiney** [comment]
Not too late at all. Thanks for the info.

I'll roll back to 6.4.x as that was where I did most of my development.

I'll have a wander around the internet to see if there is something logged
with PySide.

thanks
Peter

**Comment by pHiney** [comment]
> A bit late to this but I will say I noticed connects causing corruption and crashes in Nuitka compiles back in Pyside 6.5.1 when I put this in my code - ```

Does it work better in 6.5.2 as that is what I have installed atm.

**Comment by David-Worboys** [comment]
No, I am using 6.5.2 as well and just tested....when your video editor dumps a sqllite error, despite not using it, and crashes the app then you know it has issues!

**Comment by kayhayen** [comment]
If any of you can run the problematic version with `--experimental=disable-freelist-all` and `--debug` and factory branch code, that would be great. Seeing `functools.partial` crashing too is horrible. I was thinking it only does it to compiled methods, but maybe there is a non-Nuitka compiled method issue there, if it releases those as well. It would also trigger with the lambda if that ever got released when it shouldn't be.

**Comment by pHiney** [comment]
ok, will do

**Comment by David-Worboys** [comment]
I will give it a crack

**Comment by pHiney** [comment]
It stopped with 
```Assertion failed: _PyObject_GC_IS_TRACKED(function), file C:\git\PATHOF~1\Nuitka\nuitka\build\static_src\CompiledMethodType.c, line 572```

**Comment by David-Worboys** [comment]
Factory would not compile the app..note this is not a minimal app but I know I can crash it in a few minutes....so could not test

nuitka-crash-report.xml could not be uploaded...file type not supported, how can I send it to you?

**Comment by pHiney** [comment]
For a MRE

Grab the five files from
https://github.com/pHiney/PathOfBuilding-Python/tree/dev/scripts/tests/connections.MRE

I can run it as "c:\Temp> python connections.MRE\connections.py" outside of my main environment, with only the addition of PySide6 to the main python install, and it runs correctly.

When it is run after building an .exe it stops on

```cmd
Execute: C:\git\PathOfBuilding-Python\.venv\Lib\site-packages\PySide6\PySide6\QtCore-postLoad.py:2 <Node 'STATEMENT_RELEASE_VARIABLE_PARAMETER' with {'variable_name': 'type', 'owner': 'PySide6$QtCore$$45$postLoad$$$function__1_patched_connect'}>
Execute: C:\git\PathOfBuilding-Python\.venv\Lib\site-packages\PySide6\PySide6\QtCore-postLoad.py:2 <Node 'STATEMENT_RETURN_RETURNED_VALUE'>
Execute: c:\git\PathOfBuilding-Python\scripts\tests\connections.MRE\dialogs\browse_file_dialog.py:81 <Node 'STATEMENT_EXPRESSION_ONLY' with {'expression': 'EXPRESSION_CALL_NO_KEYWORDS'}>
Assertion failed: _PyObject_GC_IS_TRACKED(function), file C:\git\PATHOF~1\Nuitka\nuitka\build\static_src\CompiledMethodType.c, line 572
ONEFILE: Exiting.
```

To fail the program: Open the menu and select an item, it opens the file dialog - double click on a sub directory to open it. Program fails.

Question: Is it that I disconnect and reconnect triggers to stop trigger storms (tho this simple example may not, other screens do) - so you aren't tracking disconnects.

I commented out line line 162 of browse_file_dialog.py and the program behaves normally, when it is run as an .exe.

pH

**Comment by David-Worboys** [comment]
Wilco..and will report back later

**Comment by pHiney** [comment]
> Wilco..and will report back later

If you want. If was really for Kay

**Comment by David-Worboys** [comment]
:-) Have not got to it yet..might be interesting to see a MRE though!

**Comment by kayhayen** [comment]
@pHiney thanks for proving said MRE, I can indeed use it.

What I did first, was to reactivate my own code that I used to test the PySide6 workaround used for connect/disconnect issues, and I found it still works. I found a few issues with the PySide6 plugin and importing in accelerated mode, e.g. PySide6.QtWidgets didn't cause PySide6 to be compiled, and the workaround was attacked to `PySide6.QtCore` but for acceleration that is not included ever, so I moved that and then this works (with factory):

```
""" Reference counting tests.

These contain functions that do PySide6 specific things, where we have a suspect
that references may be lost or corrupted. Executing them repeatedly and
checking the reference count is how they are used.
"""

# While we use Nuitka for comparison code, no need to compile that.
# nuitka-project: --follow-imports
# nuitka-project: --nofollow-import-to=nuitka

# nuitka-project: --enable-plugin=pyside6

import sys

from PySide6.QtWidgets import QApplication, QPushButton

from nuitka.tools.testing.Common import executeReferenceChecked

app = QApplication()
button = QPushButton("Call function")

x = 17


def function():
    pass


class C:
    def meth(self):
        pass


def qtTestFunction1():
    button.clicked.connect(function)
    button.clicked.disconnect(function)


def qtTestFunction2():
    c = C()

    button.clicked.connect(c.meth)
    button.clicked.disconnect(c.meth)


####################################

# These need stderr to be wrapped.
tests_stderr = ()

# Disabled tests
tests_skipped = {}

result = executeReferenceChecked(
    prefix="qtTestFunction",
    names=globals(),
    tests_skipped=tests_skipped,
    tests_stderr=tests_stderr,
)

sys.exit(0 if result else 1)
```

If the monkey patching is not done, this will not report reference leaks, but crash for the second test part. I was a bit unsure, if that was the issue. It works the same for older and newer PySide6, so I don't believe it's that. Now probably is the time to kind of trace what actually gets connected, and if it's handled, etc. and maybe there is a different code of PySide6 in action for the components, or some of them.

**Comment by kayhayen** [comment]
So, I just realized, what might be happening, is the following. Nuitka uses a `set` of objects to protect by keeping an extra reference, such that the corruption of PySide6 to release them later one is not happening. The `set` does it only once.... that doesn't mean, you will only disconnect it once though....

**Comment by kayhayen** [comment]
I am too busy with 3.12 likely, but I wish I had taken the time to fix it upstream, but the workaround just gotten better. Now I am very unsure how to deploy that. I guess, I need to do a hotfix correction, and rebase my other changes that are for accelerated (and as such likely irrelevant) on that.

**Comment by kayhayen** [comment]
If you can, please give hotfix/1.8.4 a try.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
I am likely to push out 1.8.4 today/tomorrow with the fix for this.

**Comment by pHiney** [comment]
> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

No, it still fails.

Thanks. I'll retry 1.8.4. 
Python 3.12 will be more important.

pH

**Comment by kayhayen** [comment]
That's strange, I was pretty sure I did see the assertion go away though, retrying just now. I do remember it just quit, and that maybe too is abnormal. The change I made however has got to be good and could in fact be the reason, so I am puzzled, but of course there may be more functions of PySide6 that could expose the issue.

What I do not really like is that MiniRef.py doesn't have something added that demonstrates my fix. I believe if `c`  wasn't created anew each time, it should crash with previous code. Need to add that.

Your example now just terminates for me from the file dialog, which the Python code does not. 

Looking closer, it segfaults after returning from the file dialog here:

> 0x00007ffff6dba22d in ?? () from /home/hayen/test/PathOfBuilding-Python/scripts/tests/connections.MRE/connections.dist/PySide6/../libpyside6.abi3.so.6.5

So I am afraid, that's not all we have to do, but it clearly is better in a sense, but I noticed a thing when looking at it, and that is this bit of code:

```
                  if not receiver.im_func.__name__.startswith("_pyside6_workaround_"):
                      receiver.im_func.__name__ = "_nuitka_" + receiver.im_func.__name__
```

Which is a remnant of when we were trying to make an uncompiled wrapper function during the connection, that would then call the method, which turned out to be unworkable. So I was removing that and now it works flawlessly. Maybe something in PySide itself is upset by the code doing this to internal functions of theirs, I can assure that there is no corruption going on due to that change of `__name__` for compiled functions.

**Comment by pHiney** [comment]
Thanks I can confirm removing those two lines from the pyside6 portion of standard.nuitka-package.config.yml has made both the MRE and the main program work.

Excellent.
Thanks very much for your time.

pH

**Comment by David-Worboys** [comment]
Kay ,can confirm 1.8.4.seems to fix the issue..I switched back to using lambdas with all Qt 6.5..3 event connects that needed them and direct connects were not. 

I then  followed my test script of death and more broadly tested the app.  

I am happy to report, at this point, no crashes or obvious memory corruption. 

I do have one very minor odd issue but I suspect it is because I hot-coded a click event in a tablewidget grid to select a row by clicking on it and not just in the checkbox, now it only works with clicking in the checkbox. More than likely my code and not Nuitka.

Really appreciated your efforts on this one.

David

**Comment by pHiney** [comment]
Thank you again.
