### ISSUE TITLE
Standalone compiled project that use psycopg2 returns import error in <modulle psycopg2>

### ISSUE THREAD

**Issue by shoemak** [Nuitka/Nuitka#280]
Hello! I Have a problem with standalone compilation of my project which uses access to postgresql database through psycopg2.
Compiled project crashes with error: import error in -modulle psycopg2-
Python 3.6 32, Windows 10

![psycopg2error](https://user-images.githubusercontent.com/46621962/53554982-06dcc700-3b52-11e9-9ae3-831cf9988480.jpg)

Error appears on other win 10 computers.
If I start application exe on the computer, where I compiled it I have no errors...

**Comment by JorjMcKie** [comment]
I installed the package on my Win 10 and compile a script that does nothing but ``import psycopg2``. That one worked on the compiling Win 10 and on a different machine as well.

```
D:\Jorj\Desktop>python -m nuitka --version
0.6.3rc2
Python: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Jorj\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64

D:\Jorj\Desktop>python -m pip show psycopg2
Name: psycopg2
Version: 2.7.7
Summary: psycopg2 - Python-PostgreSQL Database Adapter
Home-page: http://initd.org/psycopg/
Author: Federico Di Gregorio
Author-email: fog@initd.org
License: LGPL with exceptions or ZPL
Location: c:\users\jorj\appdata\local\programs\python\python37\lib\site-packages
Requires:
Required-by:

D:\Jorj\Desktop>
```

**Comment by JorjMcKie** [comment]
The script:
```python
compiled = globals().get("__compiled__", False)
if compiled:
    print(
        "Running compiled (Nuitka v%i.%i.%i-%s)"
        % (compiled.major, compiled.minor, compiled.micro, compiled.releaselevel)
    )
else:
    print("Running interpreted")

import psycopg2

print("import of psycopg2 worked")
```
and the output:
```
Running compiled (Nuitka v0.6.3-candidate)
import of psycopg2 worked
```

**Comment by shoemak** [comment]
Thank you!
I will try install python 3.7 and will make simple example then inform you about results.

**Comment by JorjMcKie** [comment]
please also report your Nuitka version like I did and the install method

**Comment by shoemak** [comment]
Hello! I didn't forget about example.
I had problems with psycopg2 after standalone Nuitka compillation.
I used Python 3.6 32bit+ MS Visual Studio 2017+Nuitka 0.6.1 on Win10 (on two computers - my home notebook and work's desktop)

After JorjMcKie answered me, I decided Install 64 bit version of Python 3,7 and discovered, that appeared new Nuitka Release 0.6.2

I wrote the simpliest examle:
try: 
    import psycopg2
    print("SUCCESS!!!!!!")
except Exception as err:
    textErr = str(err.__class__.__name__) + "\n" + str(err)
    print (textErr)

But now I'm having a problem of testing my simple app on other computers with win 10.
I need to ask other people test it, but they are very busy and cannot do it quickly in all my testing versions (using different Python versions and compillers).

I used to compile my main application using MS Visual Studio 2017.
Now I decided to try MinGW64 as described in Nuitka User Manual and at the moment I'm struggling with installing Python 3,7 64 bit and compiling my main (NOT simple test script) app, using MinGW64.
I use Nuitka 0.6.2 (as I understand - it is the latest stable version).
The problem now is that on my home notebook with Win 10 this combination Python 3,7 64 bit+MinGW64+Nuitka 0.6.2. when I use Standalone compillation results in that my computer hangs/freezes, but on my work's desktop computer with Win10 Standalone compillation results in expected result (all OK) and NO problems with psycopg2 module.on the another Win 10 computer...

So... I need more time to find the causes of my problem with psycopg2 which for sure took place when I used Python 3.6 32bit+ MS Visual Studio 2017+Nuitka 0.6.1 on Win10 (on two computers - my home notebook and work's desktop)

**Comment by JorjMcKie** [comment]
Good that you are making progress overall.
I assume you have ensured compiling with a bitness that is compatible with the bitness of the target system?

**Comment by shoemak** [comment]
> Good that you are making progress overall.
> I assume you have ensured compiling with a bitness that is compatible with the bitness of the target system?
Hello! I think I have.
Most of the computer operation systems now have 64 bit, aren't they?
To my shame I'm self educated person in computers and program coding.
Some things, looking easy\simple for real IT proffesional are difficult to understand for me.

**Comment by kayhayen** [comment]
@JorjMcKie newer Nuitka checks bitness of Python vs. C compiler. Is there anything else here to do? Seems there is a lack of feedback.

**Comment by JorjMcKie** [comment]
I agree - it seems like the problem is solved or not of interest any longer.
I just tried everything again using newest version, and it continues to work:
```
D:\Jorj\Desktop\Develop\nuitka\pg-test.dist>pg-test
Running compiled (Nuitka v0.6.5-candidate)
import of psycopg2 worked

D:\Jorj\Desktop\Develop\nuitka\pg-test.dist>
```

**Comment by shoemak** [comment]
Hello! Sorry! I have really forgotten it...
I still don't understand the reason that caused the problem to appear. But now all is Ok.
Thank you! I'll close the issue.
