### ISSUE TITLE
ImportError: Could not find library zaber-motion-lib-windows-amd64.dll in bindings

### ISSUE THREAD

**Issue by 01baftb** [Nuitka/Nuitka#2824]
This issue similar to https://github.com/Nuitka/Nuitka/issues/2712 for the latest version of [zaber-motion](https://pypi.org/project/zaber-motion/). Until this is resolved, can you please suggest the content of the YAML I need to use? I tried this, https://github.com/Nuitka/Nuitka/issues/2712#issuecomment-1962080763, but it doesn't work. 

Python 3.11.9
Nuitka 2.1.6
zaber_motion 5.2.0

_Error when running .exe file:_

```powershell
PS C:\Users\abcd\build\zaber_import_issue.dist> .\zaber_import_issue.exe
Traceback (most recent call last):
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_import_issue.py", line 1, in <module>
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_motion\__init__.py", line 6, in <module zaber_motion>
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_motion\library.py", line 4, in <module zaber_motion.library>
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_motion\call.py", line 12, in <module zaber_motion.call>
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_motion\bindings.py", line 39, in <module zaber_motion.bindings>
  File "C:\Users\abcd\build\ZABER_~1.DIS\zaber_motion\bindings.py", line 35, in _load_library
ImportError: Could not find library zaber-motion-lib-windows-amd64.dll in bindings. Please contact Zaber support.
PS C:\Users\abcd\build\zaber_import_issue.dist>
```

_Test code in zaber_import_issue.py_
```python
from zaber_motion.ascii import Connection

print("Loading...")
connection = Connection.open_serial_port(port_name='COM4')
print("Done...")
```

_Compile command:_ 
```powershell
python -m nuitka --standalone --output-dir=build .\zaber_import_issue.py
```

**Comment by kayhayen** [comment]
I quickly looked at out config and it has this:

```
- module-name: 'zaber_motion' # checksum: 7af9b202
  implicit-imports:
    - depends:
        - 'zaber_motion_bindings_windows'
      when: 'win32 and version("zaber_motion") < (5,1,2)'
    - depends:
        - 'zaber_motion_bindings_linux'
      when: 'linux and version("zaber_motion") < (5,1,2)'
    - depends:
        - 'zaber_motion_bindings_darwin'
      when: 'macos and version("zaber_motion") < (5,1,2)'
    - depends:
        - 'bindings'
      when: 'version("zaber_motion") >= (5,1,2)'
```

I feel, the `bindings` should be `.bindings` or the fully qualified name, but it not effective as it is. I will quickly make that change and ask you to test it for us.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by 01baftb** [comment]
I installed the nuitka 2.2rc5 using `python -m pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"`. I am still getting the same error message. I am unsure if this helps you, but I found the DLL file in the path `<path_to_my_env>\Lib\site-packages\zaber_motion_bindings`. 

When I try using a YAML file with content you shared in https://github.com/Nuitka/Nuitka/issues/2824#issuecomment-2074153716, the compile command fails. I get the following errors: 

```python
Nuitka-Options: Used command line options: --standalone --output-dir=build --user-package-configuration-file=my_build_config.yaml .\zaber_import_issue.py
Traceback (most recent call last):
  File "<path_to_my_env>\Lib\site-packages\nuitka\plugins\Plugins.py", line 68, in withPluginProblemReporting
    yield
  File "<path_to_my_env>\Lib\site-packages\nuitka\plugins\Plugins.py", line 109, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path_to_my_env>\Lib\site-packages\nuitka\plugins\standard\AntiBloatPlugin.py", line 52, in __init__
    NuitkaYamlPluginBase.__init__(self)
  File "<path_to_my_env>\Lib\site-packages\nuitka\plugins\PluginBase.py", line 1611, in __init__
    self.config = getYamlPackageConfiguration()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path_to_my_env>\Lib\site-packages\nuitka\utils\Yaml.py", line 205, in getYamlPackageConfiguration
    _package_config.update(
  File "<path_to_my_env>\Lib\site-packages\nuitka\utils\Yaml.py", line 100, in update
    assert key not in self.data, key
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: zaber_motion
FATAL: anti-bloat: Plugin issue while working on 'Plugin initialization failed'. Please report the bug with the above traceback included.
```

**Comment by kayhayen** [comment]
It is quite possible that it doesn't fix the issue, I only corrected an obvious typo. The code you cite there, is not what we handle, quite possible that it got changes for 5.2 yet again, will have to check it out.

**Comment by kayhayen** [comment]
@KRRT7 didn't you make the original change, can you have a look, it seems they moved the DLLs again to another package, or maybe we never did the 5.1.2 change properly.

**Comment by 01baftb** [comment]
> @KRRT7 didn't you make the original change, can you have a look, it seems they moved the DLLs again to another package, or maybe we never did the 5.1.2 change properly.

I think zaber_motion did move the DLL to a different location. When I originally reported issue https://github.com/Nuitka/Nuitka/issues/2712, it was for version 4.7.0. Then I updated to version 5.1.2 and found similar issue and I posted about it in the same thread https://github.com/Nuitka/Nuitka/issues/2712#issuecomment-1962054312. In version 5.1.2 they had the DLL in a folder `/bindings`. Now in version 5.2.0, they moved the DLL to folder `/zaber_motion_bindings`.

Can you please suggest what is the content of the YAML file I need to use until the issue is resolved in an update? I tried various settings but can't figure it out.

**Comment by 01baftb** [comment]
Sorry for multiple post, but wanted to share this link, https://gitlab.com/ZaberTech/zaber-motion-lib/-/issues/23 confirms that zaber_motion did change the location of the DLL.

**Comment by KRRT7** [comment]
> Sorry for multiple post, but wanted to share this link, https://gitlab.com/ZaberTech/zaber-motion-lib/-/issues/23 confirms that zaber_motion did change the location of the DLL. Version 5.1.2 was the last version which had the DLL inside the `/bindings` folder. All versions after that have the DLL in the` /zaber_motion_bindings` folder.

yes, i opened that issue actually due to me noticing that they changed it in a heavy way, now, i wonder if the change is reflected onto the yaml, however that specific issue was for `5.1.2`, for versions greater than that, they changed it yet again. i guess that's what's missing.

**Comment by 01baftb** [comment]
> > Sorry for multiple post, but wanted to share this link, https://gitlab.com/ZaberTech/zaber-motion-lib/-/issues/23 confirms that zaber_motion did change the location of the DLL. Version 5.1.2 was the last version which had the DLL inside the `/bindings` folder. All versions after that have the DLL in the` /zaber_motion_bindings` folder.
> 
> yes, i opened that issue actually due to me noticing that they changed it in a heavy way, now, i wonder if the change is reflected onto the yaml, however that specific issue was for `5.1.2`, for versions greater than that, they changed it yet again. i guess that's what's missing.

All releases after 5.1.2 have the DLL in `zaber_motion_bindings` folder. I think the `standard.nuitka-package.config.yml` file needs to be corrected. The configuration below works for me for version 5.2.0, however please see my previous comment, https://github.com/Nuitka/Nuitka/issues/2824#issuecomment-2075794428. I cannot provide my own YAML configuration because the incorrect `standard.nuitka-package.config.yml` causes conflict. 


```yml
- module-name: "zaber_motion"
  implicit-imports:
    - depends:
        - "zaber_motion_bindings"

- module-name: "zaber_motion_bindings"
  dlls:
    - from_filenames:
        prefixes:
          - "zaber-motion-lib"
```

**Comment by kayhayen** [comment]
I manually merged @KRRT7 work, and this is on develop now and will be part of 2.2 release.

**Comment by KRRT7** [comment]
@01baftb since you're invested in this, consider adding zaber-motion as a [nuitka-watch](https://github.com/Nuitka/Nuitka-Watch/) test case which can help us catch these sort of things sooner.

**Comment by kayhayen** [comment]
@KRRT7 we could also have something simpler, imagine that for every package with configuration for DLLs, we track if the DLLs contained in that package still list the same, that should be somewhat doable and we don't run them at all then, just checking if things change. It's a compromise, not sure worth implementing, adding cases gives much more coverage, just throwing this idea around.

**Comment by 01baftb** [comment]
> I manually merged @KRRT7 work, and this is on develop now and will be part of 2.2 release.

Silly question. How do I install the dev version using pip to test its working properly?

**Comment by KRRT7** [comment]
> > I manually merged @KRRT7 work, and this is on develop now and will be part of 2.2 release.
> 
> 
> 
> Silly question. How do I install the dev version using pip to test its working properly? 

https://nuitka.net/doc/download.html#pypi
Using the GitHub zip would be simplest

**Comment by kayhayen** [comment]
Part of the 2.2 release I just made.
