### ISSUE TITLE
Generated exe does not run when using generated binary package

### ISSUE THREAD

**Issue by AESilky** [Nuitka/Nuitka#2841]
> Moved here from Discord discussion at the request of @kayhayen
> AES started discussion at 05/04/2024 8:26PM
> Responded to by KeyHayen and others through 05/07/2024 10:42AM

Generated executables, when run from a prompt, are silent for about 3 seconds and then return to the prompt, when the executable is built to rely on a binary package also created using Nuitka.

**What does work:**
If the executable is created using the .py version of the package (such that the package/modules get slurped up into the executable) it runs fine. If the .py version of the application is run using the binary package it runs fine.

**From suggestions in the Discord discussion:**
I rebuilt everything using these options (from the makefile in the project):
```
 --enable-console\
 --force-stdout-spec=exe.out.txt\
 --force-stderr-spec=exe.err.txt\
 --trace\
 --python-flag=-v --debugger
```

Doing so, I get a build warning:
```
Nuitka-Options:WARNING: The '--debugger' option has no effect outside of '--debug' without '--run' option.
```
Ignoring that, and running (with the added `--trace`), I now get a **Microsoft Visual C++ Runtime Library Assertion Failed**
[exe.err.txt](https://github.com/Nuitka/Nuitka/files/15239676/exe.err.txt)
[exe.out.txt](https://github.com/Nuitka/Nuitka/files/15239679/exe.out.txt)
 (I know I'm not supposed to include screenshots - sorry):
![image](https://github.com/Nuitka/Nuitka/assets/19332027/64625b6a-91ce-40e9-bb6d-5172bf20564b)

I now also get output in the 'out.txt' and 'err.txt' files (they were empty before). I have attached the files from a run of the **MRT.exe** application. The end of the 'err.txt' file is:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ctypes'
```
The end of the 'out.txt' file is:
```
IMPORT_HARD_CTYPES : "failed hard import of 'ctypes'"
```

== Nuitka Info
```
PS C:\proj\nuitka\PyKOB\bin\MRT.dist> python -m nuitka --version
2.2.1
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe (cl 14.3).
```

== My Project (applications) Info
The project is available in GitHub: https://github.com/MorseKOB/PyKOB/tree/es-nuitka

There is a `makefile` in the root directory (it is currently pretty bare-bones, not ready for prod, but works). In it, you can see the Nuitka options that are being used.

The *MRT* application is a pure console app. The *MKOB* application is a tkinter GUI app, but it outputs runtime information to the console. The *Configure* app is currently being built using the `.py` version of the _pykob_ package. It is a hybrid console/tkinter app.

I can provide more information about building and running these three applications as needed.

**Comment by kayhayen** [comment]
Seems, there might be an implicit dependency missing:

```
Loaded pykob.morse
import 'pykob.morse' # <class 'nuitka_module_loader'>
import ctypes # considering responsibility (find_spec)
import ctypes # denied responsibility
import ctypes # considering responsibility (find_spec)
import ctypes # denied responsibility
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ctypes'
```

But I understand pykob is your code?

**Comment by AESilky** [comment]
Yes, the pykob package and contained modules are my code.

**Comment by AESilky** [comment]
I'm not familiar with working with virtual Python environments (and therefore don't use one), but maybe I should see about getting one set up with Python 3.11 and just the things needed to run and build in. Do you think that would help?

**Comment by AESilky** [comment]
These are the imports in `pykob.morse`:
```
import sys
import codecs
from pathlib import Path
from threading import current_thread, Event, Timer
from pykob import config, log
```
(in GitHub here: https://github.com/MorseKOB/PyKOB/blob/es-nuitka/src.py/pykob/morse.py )

**Comment by AESilky** [comment]
On Discord, @krrt asked what I was doing with the .pyd and .pyi files from the pykob package build.

The package build is creating `pykob.cp311-win_amd64.pyd` and 'pykob.pyi'. I am copying them as 'pykob.pyd' and 'pykob.pyi' into the src.py directory (where the application .py files are) before using Nuitka to try to create the executables.

When the application executables are created, I copy the 'pykob.pyd' file into the 'dist' directory and then I try to run the executable.

Is there a document, help page, or something that covers exactly what to do with the '.pyd' and '.pyi' files? There is also a '.pdb' file, but I assume that it is for debugging.

**Comment by AESilky** [comment]
Given the output in the err.txt output, I added a `--include-module=ctypes` to the building of the pykob package binary. That didn't help, though the error is now `ModuleNotFoundError: No module named '_ctypes'`.

**Comment by AESilky** [comment]
ctypes is conditionally imported in `pykob.kob` with this code:
```
if sys.platform == 'win32':
    from ctypes import windll
    windll.winmm.timeBeginPeriod(1)  # set clock resoluton to 1 ms (Windows only)
```
That is the only place in all of the source that it is imported.

**Comment by kayhayen** [comment]
Yeah, `ctypes` doesn't get put into the `.pyi` file, which is a grave bug. Probably because it is standard library, and said code was not updated to consider the list of things that Nuitka doesn't automatically include.

**Comment by kayhayen** [comment]
Oh, that code actually was never updated, and uses "finalization" to get at the used modules, which is of course non-sensical these days, as we added so many more import variations, this has only become bad.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by AESilky** [comment]
I cloned from the GitHub repo to run the _factory_ branch

The applications still do not run correctly, returning to the prompt after a few seconds. The good news, there is no longer an *Assertion Failed* dialog, and the 'err.txt' is empty, but the applications are not running. Here are the builds (so you can see the options used), and I have attached the 'out.txt' from trying to run the two applications.

[MRT.out.txt](https://github.com/Nuitka/Nuitka/files/15252449/MRT.out.txt)
[MKOB.out.txt](https://github.com/Nuitka/Nuitka/files/15252455/MKOB.out.txt)

Building the pykob package:
```
/c/Program\ Files/Python311/python.exe /Users/aesil/code/Nuitka-factory/Nuitka/bin/nuitka --module src.py/pykob --include-package=pykob --output-dir=bin --enable-console --force-stdout-spec=exe.out.txt --force-stderr-spec=exe.err.txt --trace
Nuitka-Options: Used command line options: --module src.py/pykob --include-package=pykob --output-dir=bin --enable-console --force-stdout-spec=exe.out.txt
Nuitka-Options: --force-stderr-spec=exe.err.txt --trace
Nuitka: Starting Python compilation with Nuitka '2.3rc2' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.          
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.            
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 17 files (no progress information available for this stage).
Nuitka-Scons: Compiled 17 C files using clcache with 0 cache hits and 17 cache misses.
Nuitka: Keeping build directory 'bin\pykob.build'.
Nuitka: Successfully created 'bin\pykob.cp311-win_amd64.pyd'.
cp bin/pykob.pyi src.py
cp bin/pykob.*.pyd src.py/pykob.pyd
```

Building MKOB executable:
```
/c/Program\ Files/Python311/python.exe /Users/aesil/code/Nuitka-factory/Nuitka/bin/nuitka --nofollow-import-to=pykob --standalone --include-data-dir=src.py/pykob/data=pykob/data --include-data-dir=src.py/pykob/resources=pykob/resources --output-dir=bin --enable-console --force-stdout-spec=exe.out.txt --force-stderr-spec=exe.err.txt --trace --enable-console --enable-plugin=tk-inter --include-data-dir=src.py/resources=resources src.py/MKOB.pyw
Nuitka-Options: Used command line options: --nofollow-import-to=pykob --standalone --include-data-dir=src.py/pykob/data=pykob/data
Nuitka-Options: --include-data-dir=src.py/pykob/resources=pykob/resources --output-dir=bin --enable-console --force-stdout-spec=exe.out.txt
Nuitka-Options: --force-stderr-spec=exe.err.txt --trace --enable-console --enable-plugin=tk-inter --include-data-dir=src.py/resources=resources src.py/MKOB.pyw        
Nuitka: Starting Python compilation with Nuitka '2.3rc2' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.                     
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 19 files (no progress information available for this stage).
Nuitka-Scons: Compiled 19 C files using clcache with 5 cache hits and 14 cache misses.
Nuitka-Options: Included data file 'pykob\data\codetable-american.txt' due to specified data dir 'src.py/pykob/data' on command line.
Nuitka-Options: Included data file 'pykob\data\codetable-international.txt' due to specified data dir 'src.py/pykob/data' on command line.
Nuitka-Options: Included data file 'pykob\resources\clack48.wav' due to specified data dir 'src.py/pykob/resources' on command line.
Nuitka-Options: Included data file 'pykob\resources\click48.wav' due to specified data dir 'src.py/pykob/resources' on command line.
Nuitka-Options: Included data file 'pykob\resources\tone0.wav' due to specified data dir 'src.py/pykob/resources' on command line.
Nuitka-Options: Included data file 'pykob\resources\tone750.wav' due to specified data dir 'src.py/pykob/resources' on command line.
Nuitka-Options: Included data file 'resources\MorseKOB.ico' due to specified data dir 'src.py/resources' on command line.
Nuitka-Options: Included data file 'resources\mkob-icon.bmp' due to specified data dir 'src.py/resources' on command line.
Nuitka-Options: Included data file 'resources\mkob-icon.ico' due to specified data dir 'src.py/resources' on command line.
Nuitka-Options: Included data file 'resources\mkob-icon.png' due to specified data dir 'src.py/resources' on command line.
Nuitka-Options: Included data file 'resources\mkob-icon_64.png' due to specified data dir 'src.py/resources' on command line.
Nuitka-Plugins:tk-inter: Included 87 data files due to Tk needed for tkinter usage.
Nuitka-Plugins:tk-inter: Included 835 data files due to Tcl needed for tkinter usage.
Nuitka: Keeping build directory 'bin\MKOB.build'.
Nuitka: Successfully created 'bin\MKOB.dist\MKOB.exe'.
cp src.py/pykob.py* bin/MKOB.dist
```

Building MRT executable:
```
/c/Program\ Files/Python311/python.exe /Users/aesil/code/Nuitka-factory/Nuitka/bin/nuitka --nofollow-import-to=pykob --standalone --include-data-dir=src.py/pykob/data=pykob/data --include-data-dir=src.py/pykob/resources=pykob/resources --output-dir=bin --enable-console --force-stdout-spec=exe.out.txt --force-stderr-spec=exe.err.txt --trace --enable-console src.py/MRT.py
Nuitka-Options: Used command line options: --nofollow-import-to=pykob --standalone --include-data-dir=src.py/pykob/data=pykob/data
Nuitka-Options: --include-data-dir=src.py/pykob/resources=pykob/resources --output-dir=bin --enable-console --force-stdout-spec=exe.out.txt
Nuitka-Options: --force-stderr-spec=exe.err.txt --trace --enable-console src.py/MRT.py
Nuitka: Starting Python compilation with Nuitka '2.3rc2' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.                  
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 7 files (no progress information available for this stage).
Nuitka-Scons: Compiled 7 C files using clcache with 5 cache hits and 2 cache misses.
Nuitka-Options: Included data file 'pykob\data\codetable-american.txt' due to specified data dir 'src.py/pykob/data' on command line.
Nuitka-Options: Included data file 'pykob\data\codetable-international.txt' due to specified data dir 'src.py/pykob/data' on command line.
Nuitka-Options: Included data file 'pykob\resources\clack48.wav' due to specified data dir 'src.py/pykob/resources' on command line.
Nuitka-Options: Included data file 'pykob\resources\click48.wav' due to specified data dir 'src.py/pykob/resources' on command line.
Nuitka-Options: Included data file 'pykob\resources\tone0.wav' due to specified data dir 'src.py/pykob/resources' on command line.
Nuitka-Options: Included data file 'pykob\resources\tone750.wav' due to specified data dir 'src.py/pykob/resources' on command line.
Nuitka: Keeping build directory 'bin\MRT.build'.
Nuitka: Successfully created 'bin\MRT.dist\MRT.exe'.
cp src.py/pykob.py* bin/MRT.dist
```

**Comment by AESilky** [comment]
I wanted to add that I now copy the pyi file from the binary package build into the source directory before building the two applications that rely on the package.

**Comment by kayhayen** [comment]
To me the --trace output from an unknown program just makes it impossible to read anything about it. Do you have a new symptom to look at? I cannot really debug inside your code base and not with the strange build setup either. Check the typical issues if they apply and then make a new report, I consider this one resolved.

**Comment by AESilky** [comment]
The symptoms are the same as I initially reported.

> Generated executables, when run from a prompt, are silent for about 3 seconds and then return to the prompt, when the executable is built to rely on a binary package also created using Nuitka.

So, I can open an issue again with the same title I used initially.

I can take out the `--trace` if that helps.

**Comment by AESilky** [comment]
I just built without `--trace` and ran the MKOB.exe application. Now the *out.txt* and *err.txt* outputs (from the `--force-std...` options) are empty (once again).

**Comment by kayhayen** [comment]
This is part of the 2.2.2 hotfix I just made, I will release it on commercial shortly too.
