### ISSUE TITLE
Failure to delete onefile build folders on Windows

### ISSUE THREAD

**Issue by kmesdo** [Nuitka/Nuitka#2895]
OS: Win 10
Nuitka: 2.3
Python: 3.11.9
cmd:

python -m nuitka --onefile --remove-output --windows-disable-console --noinclude-dlls="*libcrypto-3.dll" --noinclude-dlls="*libcrypto-3.dll" --onefile-tempdir-spec="{TEMP}/_ZoomIt" --windows-icon-from-ico="ZoomIt.ico" --output-filename="ZoomIt" Zoomit.py

[..]
Nuitka-Onefile: Onefile payload compression ratio (28.61%) size 20772084 to 5943316.
Nuitka-Onefile: Removing onefile build directory 'Zoomit_GDI_13.onefile-build'.
Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\__main__.py", line 161, in <module>
    main()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\__main__.py", line 147, in main
    MainControl.main()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 1130, in main
    _main()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 1043, in _main
    packDistFolderToOnefile(dist_dir)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\freezer\Onefile.py", line 52, in packDistFolderToOnefile
    packDistFolderToOnefileBootstrap(onefile_output_filename, dist_dir)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\freezer\Onefile.py", line 259, in packDistFolderToOnefileBootstrap
    removeDirectory(path=source_dir, ignore_errors=False)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\utils\FileOperations.py", line 754, in removeDirectory
    shutil.rmtree(path, ignore_errors=ignore_errors)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 787, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 615, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 612, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
         ^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: 'Zoomit_GDI_13.onefile-build'
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.

I've tried two different projects, with the same result. In both cases, if I run the exe produced inside the (non-removed) 'xxx.dist' directory, it runs with no problems.

**Comment by kayhayen** [comment]
Permission error: There would have to be some sort of Windows issue, e.g., an AV tool still checking those files and not allowing us to look at them. We have an extra ball of 2.3 after a sleep of 0.1, but maybe that is insufficient for more people, in 2.3 this might have become shorter, as we realized that retrying operations after a sleep is not the solution, the delay may have become too small.

**Comment by kayhayen** [comment]
I will add retry decorations with extra reasons beside AV, e.g. dist folders, your binary may still be running (or AV checked), and that should deal with this more thoroughly and give at least some form of user dialog.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kmesdo** [comment]
I have tried the latest factory version, but it has not resolved the issue. Version used:

2.4rc1
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\User1\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

[...]
Nuitka: Starting Python compilation with Nuitka '2.4rc1' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 18 files (no progress information available for this stage).
Nuitka-Scons: Compiled 18 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 13
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 5
Nuitka-Postprocessing: Adding 3 icon(s) from icon file 'ZoomIt.ico'.
Nuitka-Postprocessing: Creating single file from dist folder, this may take a while.
Nuitka-Onefile: Running bootstrap binary compilation via Scons.
Nuitka-Scons: Onefile C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Onefile linking program with 1 files (no progress information available for this stage).
Nuitka-Scons: Compiled 1 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Postprocessing: Adding 3 icon(s) from icon file 'ZoomIt.ico'.
Nuitka-Onefile: Using compression for onefile payload.
Nuitka-Onefile: Onefile payload compression ratio (28.63%) size 20766452 to 5944926.
Nuitka-Onefile: Removing onefile build directory 'Zoomit_GDI_13.onefile-build'.
Nuitka-Onefile:WARNING: Failed to delete 'Zoomit_GDI_13.onefile-build' in attempt 1.
Disable Anti-Virus, e.g. Windows Defender for build folders.
Retrying after a second of delay.
Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 612, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Zoomit_GDI_13.onefile-build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\__main__.py", line 161, in <module>
    main()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\__main__.py", line 147, in main
    MainControl.main()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 1147, in main
    _main()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\MainControl.py", line 1050, in _main
    packDistFolderToOnefile(dist_dir)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\freezer\Onefile.py", line 52, in packDistFolderToOnefile
    packDistFolderToOnefileBootstrap(onefile_output_filename, dist_dir)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\freezer\Onefile.py", line 259, in packDistFolderToOnefileBootstrap
    removeDirectory(
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\utils\FileOperations.py", line 769, in removeDirectory
    _removeDirectory()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\utils\Utils.py", line 405, in retryingFunction
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\utils\FileOperations.py", line 752, in _removeDirectory
    shutil.rmtree(path, ignore_errors=False, onerror=onError)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 787, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 615, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\User1\AppData\Local\Programs\Python\Python311\Lib\site-packages\nuitka\utils\FileOperations.py", line 745, in onError
    last_error.append(func, path)
TypeError: list.append() takes exactly one argument (2 given)

Note: I have Windows Defender turned off and no other anti-virus software running.

**Comment by kayhayen** [comment]
Yeah, that is just a programming mistake I made. The real solution will be what is currently on factory, and to include that for 2.3.1 hotfix, namely to just use the retry decorator, avoiding the special made code entirely.
