### ISSUE TITLE
tensorflow/keras not found

### ISSUE THREAD

**Issue by potentend** [Nuitka/Nuitka#2941]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
2.3.3
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
OS: Windows
Arch: x86_64
WindowsRelease: 10

- How did you install Nuitka and Python

pip install Nuitka, Python 3.11.4 from python.org, no virtualenv

- The specific PyPI names and versions
keras                                   3.3.3
tensorflow                              2.16.1

Example:

from tensorflow.keras.models import load_model

print("hello world")

This program has no issues running on my python installation.
However, when compiled with options:
py -m nuitka --mingw64 --onefile --include-module=psutil --standalone --remove-output --assume-yes-for-downloads test.py

The program outputs:
...
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\ONEFIL~1\kerastest.py", line 1, in <module>
    from tensorflow.keras.models import load_model

  File "C:\Users\user\AppData\Local\Temp\ONEFIL~1\tensorflow\python\util\lazy_loader.py", line 210, in __getattr__
  File "C:\Users\user\AppData\Local\Temp\ONEFIL~1\tensorflow\python\util\lazy_loader.py", line 52, in _load
  File "importlib.py", line 126, in import_module
ModuleNotFoundError: No module named 'keras._tf_keras'
Edit to clarify:
It compiles successfully, this error appears in the window that opens when attempting to run the executable.

Related issues:
https://github.com/Nuitka/Nuitka/issues/1089
As well as possibly this:
https://github.com/tensorflow/tensorflow/issues/53144
I have not found a solution for this in this version of tensorflow

**Comment by potentend** [comment]
https://github.com/Nuitka/Nuitka/issues/2473
I think this is the same issue, lazy loader defined in module and then called immediately to load the module, however nuitka doesnt see that

**Comment by potentend** [comment]
Update, I finally found an import statement that successfully compiles to onefile exe: Switching from:
- from tensorflow.keras.models import load_model
To
- from keras.api.models import load_model

Allows the model to be loaded successfully. However, any attempt to use the model, such as with predict, is met with errorless crash. I cannot figure out why this is happening.

**Comment by kayhayen** [comment]
I am working on this, but other issues have been more pressing unfortunately. I believe the namespace needs to be resolved at compile time, probably, it seems tensorflow.keras is just really one of the keras modules, and Nuitka cannot see through that, but with detecting the actual keras module and resolving it at compile time, it would do it. This has been done before, but it's not so easy either. 

For now, using older tensorflow ought to work.

**Comment by potentend** [comment]
I've been working on this for some time, but I really just can't find a solution to get it to work, including older versions of Tensorflow. I think the lazy loading or whatever is causing this issue was added before some of the features I need to use in my program. I understand you're quite busy and I'd like to try to solve it myself. I believe its similar to the issue in #2473 as I said previously, and I wanted to sort of copy the solution but I could not find how you resolved it.

Currently I'm using 
import keras.api.models as models
and then:
model_a = models.load_model(file.keras)
which works,
However then model_a.predict(x) and model_a.call(x)

Both fail when compiled, and just completely crash the program. Meanwhile they run perfectly in the python interpreter
Encasing the use of the model in a try except structure does nothing to avoid the crash, and printing the exception does nothing either, which I don't understand how that is possible.

Apologies as I'm probably a bit of a novice at figuring this out, but I was wondering if you could give any loose guidelines about which paths to go down, as I've been sort of shooting at this blindly for the past month or so.

**Comment by kayhayen** [comment]
This is a case of a lazy loader, that is probably best served by aliasing. The difficulty I think with tensorflow is that's kind of hard to know what to alias to, and that's probably also why they do it. 

This messy code is what we need to emulate at compile time:

```
_tf_uses_legacy_keras = (
    _os.environ.get("TF_USE_LEGACY_KERAS", None) in ("true", "True", "1"))
setattr(_current_module, "keras", _KerasLazyLoader(globals()))
_module_dir = _module_util.get_parent_dir_for_name("keras._tf_keras.keras")
_current_module.__path__ = [_module_dir] + _current_module.__path__
if _tf_uses_legacy_keras:
  _module_dir = _module_util.get_parent_dir_for_name("tf_keras.api._v2.keras")
else:
  _module_dir = _module_util.get_parent_dir_for_name("keras.api._v2.keras")
_current_module.__path__ = [_module_dir] + _current_module.__path__
```

For extending module search paths, we got stuff.

**Comment by kayhayen** [comment]
These ones appear harmless. We should try and persist the effect of this one:

```
_tf_uses_legacy_keras = (
    _os.environ.get("TF_USE_LEGACY_KERAS", None) in ("true", "True", "1"))
```

For that I think we also got a method to force compile time environment values to persist, or at least we should have. At least it's been done before.

We then of course best disarm the actual extension of `__path__`, or else the binary will do stupid things, although it looks like `_module_util.get_parent_dir_for_name` won't be problematic there.

**Comment by kayhayen** [comment]
Arguably, the check of `TF_USE_LEGACY_KERAS` could be executed in Nuitka at compile time already, and then we can hard code what keras is aliased to, otherwise we will need to reverse the _module_dir that was added to __path__ or we need to hard code the variable name `_tf_uses_legacy_keras` to look it up.

**Comment by kayhayen** [comment]
So, actually we use to do this for `tensorflow.python.util.lazy_loader` out of which the code moved to top level it seems, so hard coding that environment is easy enough with a bit of anti-bloat config.

```
      replacements:
        '_os.environ.get("TF_USE_LEGACY_KERAS", None)': 'repr(os.environ.get("TF_USE_LEGACY_KERAS", None))'
```

**Comment by kayhayen** [comment]
Now what's funny is that `_module_dir` for my keras resolves to a non-existent directory `C:\Users\kayha\test\keras-test\Lib\site-packages\keras\api\_v2` and so that won't have any effect, which is probably good, maybe it had an effect with `tf_keras` but it doesn't with current keras. Maybe for older keras it's needed, to have a v2 API behaviour.

**Comment by kayhayen** [comment]
So, this is keras3, wich is also forced by the dependencies of 2.16.1, and that's maybe causing the issues there. I wonder why I think that 2.16 worked, did they change that in a minor version?

**Comment by kayhayen** [comment]
So, I got it to work for keras3, but I now need to make said code work with all variants, however, it would appears that if keras3 is required by 2.16.1 and we only claim support of 2.16, then maybe we just check for the keras3 to be present, and just reject legacy, I will add that.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the staging branch (Nuitka commercial) and factory branch (Nuitks standard), which are development versions under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

I would love to be able to include this in the next hotfix, even though it only works well for keras3 at this time, but I will refine it for keras2 later.

**Comment by rs-highline** [comment]
Hi @kayhayen thanks for looking into this!
I just tried it and couldn't get it to work.
Always got `FATAL: options-nanny: Error, condition 'os.getenv("TF_USE_LEGACY_KERAS", None)' for module 'tensorflow' did not evaluate to boolean result.` No matter what I tried as value or any of my rudamentary "hacks" in the standard nuitka config yml.

keras3 and the limitation to tensorflow >2.16 is perfectly fine I would say!

**Comment by kayhayen** [comment]
Oh, that's true, my condition is bad. You can remove it for now, it is not needed, not sure why I didn't have the issue, or maybe I forgot to test after adding that, my bad.

**Comment by kayhayen** [comment]
I pushed an update that should correct it to both factory and staging branches, I will now add a test case to Nuitka-Watch, so we cover tensorflow 1.6.1 and latest both (it seems 1.6 was retracted or something like that).

**Comment by rs-highline** [comment]
The build is now working again with your firx for the condition.

Unfortunately the same error persists:
`import tensorflow.keras.models`
results in
`ModuleNotFoundError: No module named 'tensorflow.keras.models'`

tested with tensorflow 2.16.1 which uses keras 3.5.0

**Comment by rs-highline** [comment]
Ok I found out what was going on.
It now resolves `from tensorflow.keras import models` correctly and works at runtime without silent crashes.

Using it like
`from tensorflow import keras
from keras.models import Sequential` however does not work and results in the same ModuleNotFoundError as reported before.

But since inside the keras package not all imports are this explicit, it now crashes with errors like:

`Traceback (most recent call last):
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 833, in __call__
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 889, in _call
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 696, in _initialize
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\eager\polymorphic_function\tracing_compilation.py", line 178, in trace_function
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\eager\polymorphic_function\tracing_compilation.py", line 283, in _maybe_define_function
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\eager\polymorphic_function\tracing_compilation.py", line 310, in _create_concrete_function
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\framework\func_graph.py", line 1059, in func_graph_from_py_func
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 599, in wrapped_fn
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\eager\polymorphic_function\autograph_util.py", line 41, in autograph_handler
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\autograph\impl\api.py", line 339, in converted_call
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\autograph\impl\api.py", line 459, in _call_unconverted
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\tensorflow\python\autograph\impl\api.py", line 643, in wrapper
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\keras\src\backend\tensorflow\trainer.py", line 108, in one_step_on_data
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\keras\src\backend\tensorflow\trainer.py", line 61, in train_step
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\keras\src\metrics\reduction_metrics.py", line 143, in update_state
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\keras\src\backend\common\variables.py", line 242, in assign_add
  File "C:\Users\KRAKE-~1\Projects\KRAKE_~1\build\MAIN~1.DIS\keras\src\backend\common\variables.py", line 404, in __add__
AttributeError: module 'keras.src.backend' has no attribute 'numpy'`

Where numpy is not the numpy package but a module in `keras/src/backend` and imported with `from keras.src import backend` and then used with `backend.numpy.somefunction()`

**Comment by kayhayen** [comment]
```
# Import everything from /api/ into keras.
from keras.api import *  # noqa: F403
from keras.api import __version__  # Import * ignores names start with "_".

# Add everything in /api/ to the module search path.
__path__.append(os.path.join(os.path.dirname(__file__), "api"))  # noqa: F405
```

So, for these `__path__` kinds of sinners, we luckily also got something, I expect the keras import to be enough as a reproducer, but seemingly that also pulls in tensorflow already, making it not a really smaller reproducer. The `keras.api` star import should make it pick up `keras.api.models` and assign to `keras.models`, and so I don't get how that's not working.

There is also this code

```
# Never autocomplete `.src` or `.api` on an imported keras object.
def __dir__():
    keys = dict.fromkeys((globals().keys()))
    keys.pop("src")
    keys.pop("api")
    return list(keys)


# Don't import `.src` or `.api` during `from keras import *`.
__all__ = [
    name
    for name in globals().keys()
    if not (name.startswith("_") or name in ("src", "api"))
]
```

But I don't think, we are affected from that, models ought to be in `__dir__` result, and definitely as an attribute, which I think is what's done. And the `__all__`  should also have it.

Something strange there, pretty sure all of this works fine normally.

**Comment by kayhayen** [comment]
So, this is a more general bug of Nuitka with imports it seems. It does accept attributes for imports, but it seems with these 2 lines, it reveals a problem

```
from keras import models
from keras.models import Sequential
```

The second line is "not-found" by Nuitka in the compilation report, and at run-time I think tries to import `keras.models` which doesn't exist as a module, but it doesn't honor attributes in that specific case. I will extra a reproducer and fix that, but I don't see that happening today, so I will release this hotfix without now and fix it right after. 

For now, this gives you an idea to workaround, but know that I hate people changing their code due to Nuitka and that I will solve this ASAP and make the next hotfix right away.

**Comment by rs-highline** [comment]
@kayhayen Hi, do you by any chance have an update on this?

Trying it with latest nuitka 2.4.8 in python 3.12.6 and tensorflow 2.16.1 still results in `AttributeError: module 'keras.src.backend' has no attribute 'numpy'` as mentioned here: https://github.com/Nuitka/Nuitka/issues/2941#issuecomment-2302542796

**Comment by kayhayen** [comment]
The fixing parts are part of the current hotfix release 2.4.9 but the importing issue, I haven't had the time to look at as much as it deserves to be looked at, due to illnesses, holidays and conferences, but I will get there I hope.

**Comment by kayhayen** [comment]
I finally found the issue, they are extending sys.path manually to include a sub-package, and that is why that import works at runtime, but at compile time cannot be resolved. With a bit of yaml configuration, we actually can inform Nuitka about such things, and now it's working and will be in 2.5 release.

**Comment by kayhayen** [comment]
Part of the 2.5 release I just made.
