### ISSUE TITLE
dylib dependency scan issues when using soundfile / libsndfile

### ISSUE THREAD

**Issue by Ivorforce** [Nuitka/Nuitka#2978]
In [my project](https://github.com/Ivorforce/ECG-Viewer), I'm using the package [soundfile](https://pypi.org/project/soundfile/). The package requires a local installation of `libsndfile`. This can be accomplished using e.g. `apt install libsndfile` or `brew install libsndfile`.

When importing the package and compiling with nuitka, the following error occurs:

```
❯ poetry run python -m nuitka --output-dir=build --onefile --macos-create-app-bundle --include-package=dash --include-package-data=dash --include-package=dash_core_components --include-package-data=dash_core_components --include-package=dash_html_components --include-package-data=dash_html_components --include-package=packaging --include-package-data=packaging --include-package=plotly --include-package-data=plotly --include-package=ecgviewer --include-package-data=ecgviewer src/ecgviewer/main.py
The currently activated Python version 3.10.2 is not supported by the project (~3.9).
Trying to find and use a compatible version.
Using python3.9 (3.9.17)
Nuitka-Options: Used command line options: --output-dir=build --onefile --macos-create-app-bundle --include-package=dash
Nuitka-Options: --include-package-data=dash --include-package=dash_core_components --include-package-data=dash_core_components
Nuitka-Options: --include-package=dash_html_components --include-package-data=dash_html_components --include-package=packaging
Nuitka-Options: --include-package-data=packaging --include-package=plotly --include-package-data=plotly --include-package=ecgviewer
Nuitka-Options: --include-package-data=ecgviewer src/ecgviewer/main.py
Nuitka:WARNING: For application bundles, you ought to specify an icon with '--macos-app-icon'.", otherwise a dock icon may not be
Nuitka:WARNING: present.
Nuitka: Starting Python compilation with Nuitka '2.4rc8' on Python '3.9' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using
Nuitka-Plugins:anti-bloat: fallback implementation.
Nuitka-Plugins:anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using
Nuitka-Plugins:anti-bloat: fallback implementation.
Nuitka-Plugins:anti-bloat: Not including 'PIL.ImageQt' automatically in order to avoid bloat, but this may cause: PIL will not be
Nuitka-Plugins:anti-bloat: able to create Qt image objects.
Nuitka-Plugins:matplotlib: Using configuration file or default backend 'macosx'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 15006 files (no progress information available for this stage).
Nuitka-Scons: Compiled 15006 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 15006
Nuitka-Plugins:dll-files: Found 1 file DLLs from kiwisolver installation.
Nuitka-Plugins:dll-files: Found 1 file DLLs from soundfile installation.
FATAL:     Error, problem with dependency scan of '~/Library/Caches/pypoetry/virtualenvs/ecg-viewer-ZneG1Rn7-py3.9/lib/python3.9/site-packages/_soundfile_data/libsndfile_x86_64.dylib' with '/usr/local/lib/libsndfile.1.dylib' please report the bug.
```

The same error also occured in a github workflow: https://github.com/Ivorforce/ECG-Viewer/actions/runs/9748479421/job/26903542049

I found related issues:

- #2577 also has issues with the `soundfile` package, but they appear to be orthogonal.
- #2580 has similar dependency tracing issues for other packages.

From information discussed in #2580, I put together a command that worked:

```
❯ export PYTHONPATH=/usr/local/Cellar/libsndfile/1.2.2/lib/:$PYTHONPATH && PYTHONPATH=/usr/local/opt/libogg/lib/:$PYTHONPATH && PYTHONPATH=/usr/local/opt/libvorbis/lib/:$PYTHONPATH && PYTHONPATH=/usr/local/opt/flac/lib/:$PYTHONPATH && PYTHONPATH=/usr/local/opt/opus/lib/:$PYTHONPATH && PYTHONPATH=/usr/local/opt/mpg123/lib/:$PYTHONPATH && PYTHONPATH=/usr/local/opt/lame/lib/:$PYTHONPATH && PYTHONPATH=/usr/local/Cellar/libvorbis/1.3.7/lib/:$PYTHONPATH && poetry run python -m nuitka --output-dir=build --onefile --macos-create-app-bundle --include-package=dash --include-package-data=dash --include-package=dash_core_components --include-package-data=dash_core_components --include-package=dash_html_components --include-package-data=dash_html_components --include-package=packaging --include-package-data=packaging --include-package=plotly --include-package-data=plotly --include-package=ecgviewer --include-package-data=ecgviewer src/ecgviewer/main.py

```

Note the inclusion of more than just `libsndfile` into the pythonpath: When running with just `PYTHONPATH=/usr/local/Cellar/libsndfile/1.2.2/lib/:$PYTHONPATH`, it fails with the same error with subsequent libraries. I tracked them down until arriving at this working command (using `otool -L` and trial and error compilation).

It may be relevant to note that `libsndfile` in `/user/local/lib` is a symlink:
```
❯ readlink -f /usr/local/lib/libsndfile.1.dylib
/usr/local/Cellar/libsndfile/1.2.2/lib/libsndfile.1.0.37.dylib
```

## Reproducibility

My repository exhibiting this bug is public: https://github.com/Ivorforce/ECG-Viewer

It is already pretty small and should be sufficient. Let me know if a more minimal reproducer is needed.

The produced `.app` file works on the same computer that built the `.app`. I have not tested whether it works if `libsndfile` was not installed on the end machine. I imagine this should not be an issue though considering nuitka packages these dylibs into the binary.

## Versions

Note that I am running nuitka from revision 40529e75be5299f7262946b57eb095a502447ee7.

```
❯ poetry run python -m nuitka --version
2.4rc8
Commercial: None
Python: 3.9.17 (main, Jun 20 2023, 17:20:08)
Flavor: Homebrew Python
Executable: /Users/lukas/Jobs/KUM/ecg-viewer/.venv/bin/python
OS: Darwin
Arch: x86_64
macOSRelease: 14.5
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

```
❯ poetry run python -m pip list -v
Package                   Version
------------------------- -----------
blinker                   1.8.2
bottle                    0.12.25
cachelib                  0.9.0
certifi                   2024.7.4
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
contourpy                 1.2.1
cycler                    0.12.1
dash                      2.17.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
ecg-viewer                0.2.0
Flask                     3.0.3
Flask-Caching             2.3.0
fonttools                 4.53.0
idna                      3.7
importlib_metadata        8.0.0
importlib_resources       6.4.0
itsdangerous              2.2.0
Jinja2                    3.1.4
kiwisolver                1.4.5
MarkupSafe                2.1.5
matplotlib                3.9.1
nest-asyncio              1.6.0
Nuitka                    2.4rc8
numpy                     1.26.4
ordered-set               4.1.0
packaging                 24.1
pandas                    2.2.2
pillow                    10.4.0
pip                       23.3.1
plotly                    5.22.0
proxy_tools               0.1.0
pycparser                 2.22
pyobjc-core               10.3.1
pyobjc-framework-Cocoa    10.3.1
pyobjc-framework-Security 10.3.1
pyobjc-framework-WebKit   10.3.1
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
pytz                      2024.1
pywebview                 5.1
requests                  2.32.3
retrying                  1.3.4
scipy                     1.13.1
setproctitle              1.3.3
setuptools                70.2.0
six                       1.16.0
soundfile                 0.12.1
tenacity                  8.4.2
typing_extensions         4.12.2
tzdata                    2024.1
urllib3                   2.2.2
Werkzeug                  3.0.3
wfdb                      4.1.2
zipp                      3.19.2
zstandard                 0.22.0
```

**Comment by kayhayen** [comment]
I made a change that should detect the Homebrew installation path. I am not at all convinced, that /usr/local/lib will be good to add as DLL source path, but that's what it's going to do for Intel systems now.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by Ivorforce** [comment]
Ok great thanks, this seems to have worked (rev 8ffad3f19c9b163d0cbf40a6438f13cf5101bda4)!

**Comment by Ivorforce** [comment]
Ok, it works now locally, but remotely on the github runner it still fails (also rev https://github.com/Nuitka/Nuitka/commit/8ffad3f19c9b163d0cbf40a6438f13cf5101bda4). I imagine that's because locally I'm using homebrew, but remotely it's using something else (install-python).

Unfortunately, I do not know how to reproduce this other than to run the action remotely. But perhaps the log is already sufficient?

```
[...]
Nuitka-Scons: Compiled 14988 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 14988
Nuitka-Plugins:dll-files: Found 1 file DLLs from kiwisolver installation.
Nuitka-Plugins:dll-files: Found 1 file DLLs from soundfile installation.
FATAL:     Error, problem with dependency scan of '~/work/ECG-Viewer/ECG-Viewer/.venv/lib/python3.9/site-packages/_soundfile_data/libsndfile_x86_64.dylib' with '/usr/local/lib/libsndfile.1.dylib' please report the bug.
```
https://github.com/Ivorforce/ECG-Viewer/actions/runs/9890803939/job/27319848775

**Comment by kayhayen** [comment]
Homebrew will be working for DLLs with 2.4 much better, but apparently not with Intel. Can you check out `getHomebrewInstallPath` and what you get for `getSystemPrefixPath` and maybe how to tell if this is where it was really installed, as I do not want to hard code paths.

**Comment by Ivorforce** [comment]
I have run an action to output the requested variables. [Here's the script I used to do so](https://github.com/Ivorforce/ECG-Viewer/blob/dylib-scan-gh-tests/src/ecgviewer/nuitka_tests.py), [using this workflow](https://github.com/Ivorforce/ECG-Viewer/actions/runs/9907601158/workflow).

This is the output on mac:
```
Executable: /Users/runner/hostedtoolcache/Python/3.9.19/x64/bin/python
Flavour: Unknown
Prefix Path: /Users/runner/hostedtoolcache/Python/3.9.19/x64
Env GH Actions: True
Is GH Action Python: False
Except Homebrew Path ().
```

Checking the code from `PythonFlavors`, I'm guessing the culprit is that the GH actions test fails, because the path to the python executable is unexpected.

You can find all 3 runs here: https://github.com/Ivorforce/ECG-Viewer/actions/runs/9907601158/job/27371638455

**Comment by kayhayen** [comment]
Ah, github is not Homebrew, so that code doesn't apply to it. I am not at all sure, I want to add support for GitHub Python to be perfect, since we are going to add the Nuitka standalone backend as a target soon enough, for which we would have full control, this would be wasted time potentially.
