### ISSUE TITLE
Nuitka does not support "mne.io.read_raw_fif" and other reader functions of mne.io

### ISSUE THREAD

**Issue by neoana** [Nuitka/Nuitka#2995]
[test_load_raw.zip](https://github.com/user-attachments/files/16161815/test_load_raw.zip)

Hi friends,
I tried to use Nuitka to package a simple program, but encountered an error. The source code, demo data used, and the Nuitka packaging command have been uploaded as a compressed file in the provided link.

test002.py
'''''
from mne.io import read_raw_fif

cc = read_raw_fif("D:/test_load_raw/demo_eeg_01-raw.fif",preload=True)
print(cc.info)
'''''

I pakaged this program using the command 
"nuitka --standalone --enable-plugin=pyside6  --noinclude-numba-mode=nofollow --module-parameter=numba-disable-jit=yes test002.py"

test002.exe was generated in the folder test002.dist, when I run test002.exe in the cmd, I got these errors:
'''
D:\test_load_raw\test002.dist>test002.exe
Opening raw data file D:/test_load_raw/demo_eeg_01-raw.fif...
    Read a total of 1 projection items:
        Average EEG reference (1 x 60)  idle
    Range : 6450 ... 48149 =     42.956 ...   320.665 secs
Ready.
Traceback (most recent call last):
  File "D:\test_load_raw\test002.dist\test002.py", line 3, in <module>
  File "D:\test_load_raw\test002.dist\mne\io\fiff\raw.py", line 537, in read_raw_fif
  File "<decorator-gen-202>", line 12, in __init__
  File "D:\test_load_raw\test002.dist\mne\io\fiff\raw.py", line 127, in __init__
  File "<decorator-gen-184>", line 12, in __init__
  File "D:\test_load_raw\test002.dist\mne\io\base.py", line 310, in __init__
  File "D:\test_load_raw\test002.dist\mne\utils\misc.py", line 318, in _get_argvalues
KeyError: 'self'
'''

This is a snippet of a project program, and the rest of the parts have been successfully packaged and can run normally. However, the function mne.io.read_raw_fif is causing an exception when executed. Please help check the issue. Thank you.

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
2.3.11
Commercial: None
Python: 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:42:21) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\Test\anaconda3\envs\myenv\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe (cl 14.3).

- How did you install Nuitka and Python
Nuitka was installed in a anaconda environment using  "pip install nuitka"

- The specific PyPI names and versions
  > python -m pip list -v
Package                   Version        Location                                                  Installer
------------------------- -------------- --------------------------------------------------------- ---------
altgraph                  0.17.4         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
antropy                   0.1.6          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
anyio                     4.4.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
argon2-cffi               23.1.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
argon2-cffi-bindings      21.2.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
arrow                     1.3.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
asttokens                 2.4.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
async-lru                 2.0.4          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
attrs                     23.2.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
Babel                     2.15.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
beautifulsoup4            4.12.3         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
bleach                    6.1.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
Bottleneck                1.3.7          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages conda
certifi                   2024.6.2       C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
cffi                      1.16.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
charset-normalizer        3.3.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
colorama                  0.4.6          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
colorcet                  3.1.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
comm                      0.2.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
contourpy                 1.2.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
cycler                    0.12.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
darkdetect                0.8.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
debugpy                   1.8.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
decorator                 5.1.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
defusedxml                0.7.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
edfio                     0.4.3          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
eeglabio                  0.0.2.post4    C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
et-xmlfile                1.1.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
executing                 2.0.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
fastjsonschema            2.19.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
fonttools                 4.53.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
fooof                     1.1.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
fqdn                      1.5.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
h11                       0.14.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
h5py                      3.11.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
httpcore                  1.0.5          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
httpx                     0.27.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
idna                      3.7            C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
imageio                   2.34.2         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
ipykernel                 6.29.4         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
ipywidgets                8.1.3          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
isoduration               20.11.0        C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jedi                      0.19.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
Jinja2                    3.1.4          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
joblib                    1.4.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
json5                     0.9.25         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jsonpointer               2.4            C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jsonschema                4.22.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jsonschema-specifications 2023.12.1      C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyter                   1.0.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyter_client            8.6.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyter-console           6.6.3          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyter_core              5.7.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyter-events            0.10.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyter-lsp               2.2.5          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyter_server            2.14.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyter_server_terminals  0.5.3          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyterlab                4.2.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyterlab_pygments       0.3.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyterlab_server         2.27.2         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
jupyterlab_widgets        3.0.11         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
kiwisolver                1.4.5          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
lazy_loader               0.4            C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
llvmlite                  0.42.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
MarkupSafe                2.1.5          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
matplotlib                3.9.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
matplotlib-inline         0.1.7          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
mistune                   3.0.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
mkl-fft                   1.3.8          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages conda
mkl-random                1.2.4          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages conda
mkl-service               2.4.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages
mne                       1.7.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
nbclient                  0.10.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
nbconvert                 7.16.4         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
nbformat                  5.10.4         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
nest-asyncio              1.6.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
notebook                  7.2.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
notebook_shim             0.2.4          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
Nuitka                    2.3.11         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
numba                     0.59.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
numexpr                   2.8.7          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages conda
numpy                     1.26.4         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages conda
openpyxl                  3.1.3          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
ordered-set               4.1.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
overrides                 7.7.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
packaging                 24.0           C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pandas                    2.2.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages conda
pandocfilters             1.5.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
parso                     0.8.4          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pefile                    2023.2.7       C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
phyaat                    0.0.3          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pillow                    10.3.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pip                       24.1.2         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
platformdirs              4.2.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pooch                     1.8.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
prometheus_client         0.20.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
prompt_toolkit            3.0.46         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
psutil                    5.9.8          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pure-eval                 0.2.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pyarmor.cli.core          6.5.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pybv                      0.7.5          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pycparser                 2.22           C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
Pygments                  2.18.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pyinstaller               6.9.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pyinstaller-hooks-contrib 2024.7         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pylfsr                    1.0.7          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pyparsing                 3.1.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pyqtgraph                 0.13.7         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
PySide6                   6.7.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
PySide6_Addons            6.7.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
PySide6_Essentials        6.7.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
python-dateutil           2.9.0.post0    C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages conda
python-json-logger        2.0.7          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
python-picard             0.7            C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pytz                      2024.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages conda
PyWavelets                1.6.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pywin32                   306            C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pywin32-ctypes            0.2.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pywinpty                  2.0.13         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
PyYAML                    6.0.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
pyzmq                     26.0.3         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
QDarkStyle                3.2.3          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
qtconsole                 5.5.2          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
QtPy                      2.4.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
referencing               0.35.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
requests                  2.32.3         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
rfc3339-validator         0.1.4          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
rfc3986-validator         0.1.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
rpds-py                   0.18.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
scikit-learn              1.5.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
scipy                     1.13.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
scooby                    0.10.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
seaborn                   0.13.2         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
Send2Trash                1.8.3          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
setuptools                69.5.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages
shiboken6                 6.7.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
six                       1.16.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages conda
sniffio                   1.3.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
soupsieve                 2.5            C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
spkit                     0.0.9.6.7      C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
stack-data                0.6.3          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
stochastic                0.6.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
terminado                 0.18.1         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
threadpoolctl             3.5.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
tinycss2                  1.3.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
tornado                   6.4.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
tqdm                      4.66.4         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
traitlets                 5.14.3         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
types-python-dateutil     2.9.0.20240316 C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
tzdata                    2023.3         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages conda
uri-template              1.3.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
urllib3                   2.2.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
wcwidth                   0.2.13         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
webcolors                 24.6.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
webencodings              0.5.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
websocket-client          1.8.0          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
wheel                     0.43.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages
widgetsnbextension        4.0.11         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
WMI                       1.5.1          C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip
zstandard                 0.22.0         C:\Users\Test\anaconda3\envs\fusionana\Lib\site-packages pip

**Comment by kayhayen** [comment]
For this, I would need a raw FIF file, which I was not immediately capable of locating one. Can you provide a small example to reproduce it?

**Comment by H0I00** [comment]
2.4.10
Commercial: None
Python: 3.11.10 | packaged by Anaconda, Inc. | (main, Oct  3 2024, 07:22:26) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\12474\.conda\envs\package\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Nuitka-Scons: Non downloaded winlibs-gcc 'C:\msys64\ucrt64\bin\gcc.exe' is being ignored, Nuitka is very dependent on the precise one.
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

It's not just the fif file, I also have the same problem when I use mne.io.read_raw_edf to read the edf file. I have a lot of sample files that I can provide, but I don't want to make them public. How can I contact you?

**Comment by kayhayen** [comment]
I need a reproducer, and I think I am not sure what file types to trust there, I don't want to execute code, and with these tools, the files might be code, so I better would like a public example from upstream there, if any such thing exists.

**Comment by H0I00** [comment]
mne also comes with its own sample dataset, located at https://mne.tools/stable/documentation/datasets.html, using the common fif format (the format most supported by mne)

**Comment by kayhayen** [comment]
Thanks, I managed to get an example from there with a FIF file, maybe now I can reproduce things.

**Comment by kayhayen** [comment]
It seems there is only a *single* use of that function, the one we are seeing, and just to create a function that automates assigning a few parameter variables.

**Comment by kayhayen** [comment]
So, this is looking at parent class arguments, so I get what they want to do there, and we need to put this kind of code before calling the base class:

`__import__("inspect").currentframe().f_locals.update(locals())`

That ought to make things work. Unfortunately that will have to be done for all derived classes. I only found the fif raw now, checking the edf case if this works too.

**Comment by kayhayen** [comment]
So, I added workarounds for the raw.raw and edf.edf, and tested the first one, I would hope for @H0I00 to confirm if it works with that.

My example program displays a plot, for which package data might have to be included, but also mne works fine without any of that, so I didn't bother to make these included by default.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by H0I00** [comment]
I tested mff, edf, cdt, bdf files, edf and bdf can be read successfully, but mff and cdt still have problems.
At least my software can be used, thank you for your contribution

**Comment by H0I00** [comment]
The cdt file can be used, but the mff file still has problems. The reason may be that in the Windows system, the mff file is actually a folder ending with .mff.
![Uploading MFF.png…]()

**Comment by kayhayen** [comment]
Nah, maybe I just messed up the module name, I will check again.

**Comment by kayhayen** [comment]
Nah, it's good, can you point to an example from the link you gave that uses .mff so I can see for myself, the correction I added should be effective, but it might not be the only one needed.

**Comment by H0I00** [comment]
Here is how to download the mff data: https://mne.tools/dev/auto_tutorials/preprocessing/90_eyetracking_data.html#sphx-glr-auto-tutorials-preprocessing-90-eyetracking-data-py

And the reading function: https://mne.tools/stable/generated/mne.io.read_raw_egi.html

**Comment by kayhayen** [comment]
Ok, with this, I managed it. Let me know if any other thing is still missing there (by opening another issue, should this one become closed).

**Comment by H0I00** [comment]
Please check the ica.plot_sources function, the usage is located at https://mne.tools/stable/generated/mne.preprocessing.ICA.html#mne.preprocessing.ICA.plot_sources
Specific examples can be seen:
https://mne.tools/stable/auto_examples/preprocessing/muscle_ica.html#sphx-glr-auto-examples-preprocessing-muscle-ica-py

As when reading data, when I try to get the error with except Exception as e, only "self" is captured

**Comment by kayhayen** [comment]
I'd love to also add these things to Nuitka-Watch. They download stuff, which I would want to use cached, maybe added to the repo. Can you give me a hint, how to force (mne, huggingface hub or whatever is used there) to load/store from another folder?

**Comment by H0I00** [comment]
Thank you for your concern about the mne package related issues. Do you mean to download a copy of the data and save it permanently instead of downloading the data from the code every time? This is a more mature manual, which also provides a link to download classic data in EEGLAB: https://github.com/ZitongLu1996/Python-EEG-Handbook/blob/master/EEG_Python_Handbook_Preprocessing.ipynb

**Comment by kayhayen** [comment]
Ah, I found `SENTENCE_TRANSFORMERS_HOME` and now of course, need to find some small models to add to the repo, more like 10MB and not 100MB, which is what I have from an earlier test.

**Comment by kayhayen** [comment]
I see there are sample data paths used in the last example you pointed to, so a pip install probably pulls those in already, they are of course best to use for me, since they are not an extra download and licensing also not an issue I guess.

**Comment by kayhayen** [comment]
Oh, I see, that's downloads still, and large ones, so that's pretty impossible to use for regular jobs on CI.

**Comment by kayhayen** [comment]
The changes so far are part of the current pre-release and will be part of 2.5 release. I will be looking at your latest code soon.

**Comment by HeHaina** [comment]
I also encountered the same issue when using the ica.plot_sources function from MNE, receiving the same error ("self"). I hope to find a solution. Attached is the minimal code and my data.
Thanks
[ICACA.zip](https://github.com/user-attachments/files/17703245/ICACA.zip)

**Comment by kayhayen** [comment]
@HeHaina did you try the current develop version?

**Comment by HeHaina** [comment]
@kayhayen Sorry sir,maybe it does not worked.Following your suggestion, I updated the library and tested the minimal code where the issue occurs. Unfortunately, I found that the same error ("self") persists, indicating that the problem remains unresolved. I have attached a screenshot to illustrate the error for your reference.

Below is my configuration：
2.5rc13
Commercial: None
Python: 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\Anaconda3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\14.2.0posix-19.1.1-12.0.0-msvcrt-r2\mingw64\bin\gcc.exe (gcc 14.2.0).

I would greatly appreciate any assistance you can provide in resolving this issue. Thank you very much for your continued support, and I look forward to your guidance.
Best regards

![test](https://github.com/user-attachments/assets/063ce5ef-059b-440f-a3d4-cf289717f715)

**Comment by kayhayen** [comment]
@HeHaina seems like a different issue, please create a new issue and make a complete report there filling out the issue template, as otherwise I will loose track of things, since this one is about to get closed as it's about reading and this seems something else in processing

**Comment by HeHaina** [comment]
Sorry sir,I have created a new issue  #3191 to report it

**Comment by kayhayen** [comment]
Part of the 2.5 release I just made.
