### ISSUE TITLE
Executable Paths Including Spaces Break sys.argv on Windows

### ISSUE THREAD

**Issue by NinjaCheetah** [Nuitka/Nuitka#3028]
**Nuitka Version:**
```
2.4.2
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\campb\Documents\Code\Python\WiiPy\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe (cl 14.3).
```
Installed normally from PyPI.

**Description:**
When running an executable compiled with Nuitka 2.4+ on Windows, any spaces in the path to the executable will result in separations in sys.argv, meaning that the executable cannot be used under most conditions. This is likely related to #3021, which involved spaces in arguments causing separations in sys.argv, however this is still occurring even with that issue fixed. This worked in Nuitka 2.3.11 and older. This issue is not present on Linux or macOS.

**Command:** `program.exe --help`, located at `C:\my folder\program.exe`

**Value of `sys.argv`:**
Nuitka 2.3.11: `['C:\\my folder\\program.exe', '--help']`
Nuitka 2.4+: `['C:\\my', 'folder\\program.exe', '--help']`

The program is still able to execute, but especially when relying on `argparse` `sys.argv[1]` being the rest of the executable path means that your first argument is always invalid, preventing the program from being usable.

**Comment by Dnyarri** [comment]
Interesting finding. I just tried to change file path requests to `f'"{argv[1]}"'` - nope, doesn't seem to help.

**Comment by kayhayen** [comment]
Ah, for argv[0] the escaping added for the other arguments is not properly happening, my bad, I will need to add that too.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
Please confirm, this will be on an emergency hotfix of course.

**Comment by Choonholic** [comment]
**Not fixed** even occurs with nuitka 2.3.11.

Directory: `C:\Users\Choonholic\Documents\GitHub\DownloaderSuite\ref\test folder`
File name: `n test.exe`
Arguments: `"argv1 abc" argv2`

**Expected:**
`['C:\\Users\\Choonholic\\Documents\\GitHub\\DownloaderSuite\\ref\\test folder\\n test.exe', 'argv1 abc', 'argv2']`

**Version 2.4.3:**
`['C:\\Users\\Choonholic\\Documents\\GitHub\\DownloaderSuite\\ref\\test', 'folder\\n', 'test.exe', 'argv1 abc', 'argv2']`

**Factory Build:**
`['C:\\Users\\Choonholic\\Documents\\GitHub\\DownloaderSuite\\ref\\test', 'folder\\n', 'test.exe', 'argv1 abc', 'argv2']`

**Version 2.3.11:**
`['C:\\Users\\Choonholic\\Documents\\GitHub\\DownloaderSuite\\ref\\test', 'folder\\n', 'test.exe', 'argv1 abc', 'argv2']`

Plus, even renamed file to `ntest.exe` (2.3.11):
`['C:\\Users\\Choonholic\\Documents\\GitHub\\DownloaderSuite\\ref\\test', 'folder\\ntest.exe', 'argv1 abc', 'argv2']`

Should be checked again.
Thanks.

**Comment by Choonholic** [comment]
@kayhayen 

Sorry for incorrect confirmation.
**Fixed ** in factory build like below:

```
PS C:\Users\Choonholic\Documents\GitHub\DownloaderSuite\ref\test folder> & '.\n test.exe' "argv1 abc" argv2
['C:\\Users\\Choonholic\\Documents\\GitHub\\DownloaderSuite\\ref\\test folder\\n test.exe', 'argv1 abc', 'argv2']
```

**Comment by kayhayen** [comment]
Part of the 2.4.4 hotfix I just made
