### ISSUE TITLE
Traits crashes at runtime when compiled with Nuitka on macOS

### ISSUE THREAD

**Issue by YomGarcia** [Nuitka/Nuitka#3433]
Hi all! 
Thank you for this amazing piece of software. I am facing an issue which seems to be related to the way [traits and traitsui](https://github.com/enthought/traits) are handled by nuitka, which would be understandable given the dynamic nature of `traits`.

[edit] : removed `traitsui` related imports in the provided example as they are not relevant 

### Problem

When compiling a minimal TraitsUI app using Nuitka on macOS, the resulting `main.app/Contents/MacOS/main` executable crashes at runtime with the following error:

```bash
$ ./main.app/Contents/MacOS/main                                       
Traceback (most recent call last):
  File "main.app/Contents/MacOS/main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "main.app/Contents/MacOS/traitsui/api.py", line 257, in <module traitsui.api>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "main.app/Contents/MacOS/traitsui/editors/api.py", line 93, in <module traitsui.editors.api>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "main.app/Contents/MacOS/traitsui/editors/boolean_editor.py", line 15, in <module traitsui.editors.boolean_editor>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "main.app/Contents/MacOS/traitsui/editors/text_editor.py", line 44, in <module traitsui.editors.text_editor>
  File "main.app/Contents/MacOS/traitsui/editors/text_editor.py", line 96, in TextEditor
  File "main.app/Contents/MacOS/traitsui/view.py", line 345, in __init__
  File "main.app/Contents/MacOS/traitsui/view.py", line 355, in set_content
  File "main.app/Contents/MacOS/traitsui/group.py", line 224, in __init__
  File "main.app/Contents/MacOS/traitsui/item.py", line 262, in __init__
  File "main.app/Contents/MacOS/traits/has_traits.py", line 3302, in _init_trait_listeners
  File "main.app/Contents/MacOS/traits/has_traits.py", line 3369, in _init_trait_delegate_listener
  File "main.app/Contents/MacOS/traits/has_traits.py", line 2640, in on_trait_change
  File "main.app/Contents/MacOS/traits/traits_listener.py", line 428, in register
  File "main.app/Contents/MacOS/traits/traits_listener.py", line 599, in _register_simple
  File "main.app/Contents/MacOS/traits/has_traits.py", line 2260, in _on_trait_change
  File "main.app/Contents/MacOS/traits/trait_notifiers.py", line 413, in __init__
  File "main.app/Contents/MacOS/traits/trait_notifiers.py", line 450, in init
traits.trait_errors.TraitNotificationError: Invalid number of arguments for the dynamic trait change notification handler: handle_simple. A maximum of 4 arguments is allowed, but 5 were specified.
```

### System Specs

- OS : MacOS Sequoia 15.2
- Python is provided by miniforge
- Nuitka is provided by pip

```bash
$ python -m nuitka --version
2.6.9
Commercial: None
Python: 3.12.10 | packaged by conda-forge | (main, Apr 10 2025, 22:19:24) [Clang 18.1.8 ]
Flavor: Anaconda Python
Executable: ~/miniforge3/envs/utils/bin/python
OS: Darwin
Arch: arm64
macOSRelease: 15.2
Version C compiler: /usr/bin/clang (clang 16.0.0).> python -m nuitka --version
```

```bash
$ python -m pip list -v
Package     Version Location                                                             Installer
----------- ------- -------------------------------------------------------------------- ---------
Nuitka      2.6.9   /Users/guillaume/miniforge3/envs/report/lib/python3.12/site-packages pip
ordered-set 4.1.0   /Users/guillaume/miniforge3/envs/report/lib/python3.12/site-packages pip
pip         25.0.1  /Users/guillaume/miniforge3/envs/report/lib/python3.12/site-packages conda
pyface      8.0.0   /Users/guillaume/miniforge3/envs/report/lib/python3.12/site-packages pip
setuptools  78.1.0  /Users/guillaume/miniforge3/envs/report/lib/python3.12/site-packages
traits      7.0.2   /Users/guillaume/miniforge3/envs/report/lib/python3.12/site-packages pip
traitsui    8.0.0   /Users/guillaume/miniforge3/envs/report/lib/python3.12/site-packages pip
wheel       0.45.1  /Users/guillaume/miniforge3/envs/report/lib/python3.12/site-packages
zstandard   0.23.0  /Users/guillaume/miniforge3/envs/report/lib/python3.12/site-packages pip
```

### How to reproduce

I am compiling the following example, within the conda environment above with the command:
```bash
$ nuitka main.py --macos-create-app-bundle --macos-app-icon=none
```

```python 
from traits.api import HasTraits, Str, Instance, observe
from traitsui.api import View

class Person(HasTraits):
    name = Str()

    @observe('name')
    def on_name_changed(self, event):
        print(f"[Person] Name changed from {event.old!r} to {event.new!r}")

class Company(HasTraits):
    ceo = Instance(Person)

    @observe('ceo')
    def on_ceo_changed(self, event):
        print(f"[Company] CEO changed from {event.old!r} to {event.new!r}")

    @observe('ceo.name')
    def on_ceo_name_changed(self, event):
        print(f"[Company] CEO's name changed from {event.old!r} to {event.new!r}")



if __name__ == "__main__":
    alice = Person(name="Alice")
    company = Company(ceo=alice)
    company.configure_traits()
```

### Notes

- This error does not occur when running the same file via python main.py.
- It does occur even with `@observe` removed and replaced by `_xxx_changed()` methods.
- Seems to stem from how `handle_simple()` is compiled or wrapped dynamically.

### Request

Can Nuitka add compatibility with TraitsUI's dynamic notification handler system, or provide a workaround to suppress/fix this error? Thank you in advance, keep up the good work!

**Comment by mdickinson** [comment]
Some details are here: https://github.com/enthought/traits/issues/1848

The root of the issue appears to be that Traits is inspecting `func.__code__.co_argcount` on a particular method of a Python class, and getting an unexpected answer of `6`, where the method in question clearly has only 5 parameters (including `self`). Here's a direct link to that method:

https://github.com/enthought/traits/blob/86cdb2f8e10836b17db590da50418a340b55481b/traits/traits_listener.py#L450-L454

Question: is `__code__.co_argcount` supported by Nuitka? Is the wrong value somehow a result of some optimization performed by Nuitka?

**Comment by YomGarcia** [comment]
Hi,
I already know paid support can give priority to this issue. Any idea on how likely would it be addressed and eventually solved if I choose such support option?

**Comment by kayhayen** [comment]
> Hi, I already know paid support can give priority to this issue. Any idea on how likely would it be addressed and eventually solved if I choose such support option?

Yes it would. Recently I have been falling behind on issues due to private issues, and then it would indeed have helped a lot, but with me now catching up, compatability is something I work on with priority most of the time anyway to be honest. However, support can help me expand getting help so I have more time to work on stuff.

**Comment by kayhayen** [comment]
So, my quick test of said function co_argcount gave the proper answer. I think everything else would have been extremely surprising of course.

**Comment by kayhayen** [comment]
I even went back to 2.6.9, not reproducing with my current 2.8 development build (2.7 has since been released, and I couldn't reproduce it with that version either, now trying Anaconda, which hasn't done anything like that in a while, but I will give it a go, since this seems like a somewhat reasonable report.

**Comment by kayhayen** [comment]
Maybe your miniforge Python wasn't healthy or something like that, but I cannot reproduce it. My Anaconda Python 3.12 also works just fine. If you can come up with something reproducible, that would be great.

**Comment by YomGarcia** [comment]
Apologies, the example I posted actually works as it does not rely on any of `traitsui` features.
I updated the example. `configure_traits()` is the traitsui method that allows the user to modify a traits through the interface and calling the executable obatined out of `nuitka main.py --macos-create-app-bundle --macos-app-icon=none` shoud show thr trace I posted.

**Comment by mdickinson** [comment]
FWIW, I could reproduce @YomGarcia's issue without any Anaconda involvement.

It ought to be possible to slowly bisect the Traits content to produce a minimal reproducer - in particular, I don't _think_ the relevant code is making significant use of the Traits C extension, so there should be a pure Python reproducer possible.

That said, I'm afraid I don't have the bandwidth to do that bisection (my boss would rightly be asking why I was spending company time on this).

**Comment by YomGarcia** [comment]
I may have fixed the issue.
I am waiting for enthought feedback, but it seems it was coming from traits handling compiled methods differently
See https://github.com/enthought/traits/pull/1850

**Comment by kayhayen** [comment]
We could add a Nuitka package configuration that makes that change during compilation for the older versions too.

**Comment by YomGarcia** [comment]
How would you like to proceed in order to add such a configuration?

**Comment by kayhayen** [comment]
You would do it according to this: https://nuitka.net/user-documentation/nuitka-package-config.html#id8

There are plenty of examples for `replacement_plain`  in the existing packaging file. Basically all that would be needed is to take the diff and replace the expressions changed with the new ones. For the corrected code it wouldn't make a difference, but old ones would start to work.

Honestly what would be very nice would be a tool in Nuitka to either create replacements from a patch, or to have a config that applies a patch. Typically patches are more fragile or rather fragile in a different way (checking too little vs. too much context).

**Comment by kayhayen** [comment]
For reference, the patch is this: https://github.com/enthought/traits/pull/1850/commits/b557d0a4d0cd3296d7b1d824f65ca07d2a1f1944

**Comment by kayhayen** [comment]
I came up with this config

```
- module-name: 'traits.modifiers' # checksum: 6677774e
  anti-bloat:
    - description: 'support older traits package'
      replacements_plain:
        'type(handler) is MethodType': 'isinstance(handler, MethodType)'
```

Let me know if that works with old traits package, I will put this into 2.8 so we have universal compatibility without forcing people into upgrades.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 
	
Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
If would be nice if somebody confirmed it works pre-upstream fix indeed so I can then close it for 2.8 release

**Comment by YomGarcia** [comment]
I just checked with 2.8rc15 on `traits==7.0.2` and the crash still occurs
```
$ ./traitsTest.app/Contents/MacOS/traitsTest
Traceback (most recent call last):
  File "/private/tmp/traitsTest.app/Contents/MacOS/traitsTest.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/private/tmp/traitsTest.app/Contents/MacOS/traitsui/api.py", line 257, in <module traitsui.api>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/private/tmp/traitsTest.app/Contents/MacOS/traitsui/editors/api.py", line 93, in <module traitsui.editors.api>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/private/tmp/traitsTest.app/Contents/MacOS/traitsui/editors/boolean_editor.py", line 15, in <module traitsui.editors.boolean_editor>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/private/tmp/traitsTest.app/Contents/MacOS/traitsui/editors/text_editor.py", line 44, in <module traitsui.editors.text_editor>
  File "/private/tmp/traitsTest.app/Contents/MacOS/traitsui/editors/text_editor.py", line 96, in TextEditor
  File "/private/tmp/traitsTest.app/Contents/MacOS/traitsui/view.py", line 345, in __init__
  File "/private/tmp/traitsTest.app/Contents/MacOS/traitsui/view.py", line 355, in set_content
  File "/private/tmp/traitsTest.app/Contents/MacOS/traitsui/group.py", line 224, in __init__
  File "/private/tmp/traitsTest.app/Contents/MacOS/traitsui/item.py", line 262, in __init__
  File "/private/tmp/traitsTest.app/Contents/MacOS/traits/has_traits.py", line 3302, in _init_trait_listeners
  File "/private/tmp/traitsTest.app/Contents/MacOS/traits/has_traits.py", line 3369, in _init_trait_delegate_listener
  File "/private/tmp/traitsTest.app/Contents/MacOS/traits/has_traits.py", line 2640, in on_trait_change
  File "/private/tmp/traitsTest.app/Contents/MacOS/traits/traits_listener.py", line 428, in register
  File "/private/tmp/traitsTest.app/Contents/MacOS/traits/traits_listener.py", line 599, in _register_simple
  File "/private/tmp/traitsTest.app/Contents/MacOS/traits/has_traits.py", line 2260, in _on_trait_change
  File "/private/tmp/traitsTest.app/Contents/MacOS/traits/trait_notifiers.py", line 413, in __init__
  File "/private/tmp/traitsTest.app/Contents/MacOS/traits/trait_notifiers.py", line 450, in init
traits.trait_errors.TraitNotificationError: Invalid number of arguments for the dynamic trait change notification handler: handle_simple. A maximum of 4 arguments is allowed, but 5 were specified.
```

**Comment by kayhayen** [comment]
Thanks, seems I had to actually run the test case to get it right. I also did a bit of work on anti-bloat, including metadata and adding a few dependencies, however the example didn't run for me really, seems I am using the null backend for whatever reason. If anybody were to open an new issue with a proper example, I would love to get it properly solved, but for now the errors reported will be gone.

You can retry factory, and old traits package will now work too.

**Comment by kayhayen** [comment]
This is now on the develop branch and will be part of the 2.8 release.

**Comment by kayhayen** [comment]
This is part of the stable release 2.8 that I just made. 

I would still love to have confirmation about old traits if anybody were so kind, but I believe it ought to work now.

**Comment by YomGarcia** [comment]
Yes, from a clean `nuitka==2.8` and `traits==7.0.2` install (which is before the fix on their part) I confirm this crash is not observed anymore.
Thank you 👍
