### ISSUE TITLE
Not support py3.6/3.7 Fatal Python error: Py_Initialize: Unable to get the locale encoding

### ISSUE THREAD

**Issue by zb12138** [Nuitka/Nuitka#3545]
Python version: (created by conda)
```
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  
```
nuitka version
```
'2.8rc10'
```

hello.py
```
print('hello')
```

cmd
```
python -m nuitka hello.py 
```

output
```
Nuitka-Options: Used command line options:
Nuitka-Options:   hello.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with:
Nuitka:   Version '2.8rc10' on Python 3.6 (flavor 'Anaconda Python') commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.    
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.      
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 7).
Nuitka-Scons: Backend C linking with 7 files (no progress information available for this stage).
/usr/bin/ld: warning: /home/staff/user/miniconda3/envs/py36/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/usr/bin/ld: warning: /home/staff/user/miniconda3/envs/py36/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/usr/bin/ld: warning: /home/staff/user/miniconda3/envs/py36/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/usr/bin/ld: warning: /home/staff/user/miniconda3/envs/py36/lib/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install
Nuitka-Scons:WARNING: it.
Nuitka: Keeping build directory 'hello.build'.
Nuitka: Successfully created 'hello.bin'.
```

error
```
(py36) $ ./hello.bin 
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f1d7e589740 (most recent call first):
Aborted (core dumped)
```
expect:
```
hello
```
It worked fine in py3.8. I encountered this issue on multiple machines, so I don't think it's an environment problem.

**Comment by kayhayen** [comment]
That is accelerated mode only, which would need help to find the Python home. It seems to not recognize it as uninstalled Python for some reason.

**Comment by kayhayen** [comment]
It's a statically linked Python, and those don't get that treatment, however that's not relevant really for Anaconda.

**Comment by kayhayen** [comment]
Chances are you didn't mean to not use standalone mode, but it will work now.

Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 
	
Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
This is part of the stable release 2.8 that I just made.

**Comment by zb12138** [comment]
Sorry, I tested the factory version. But it still does not work if you run hello.bin. It seem need runing hello.sh, then it works. 

Name: Nuitka
Version: 2.9rc1
Summary: Python compiler with full language support and CPython compatibility
Home-page: https://nuitka.net
Author: Kay Hayen
Author-email: Kay.Hayen@gmail.com
License: Apache License, Version 2.0
Location: /home/fuchy/miniconda3/envs/py37/lib/python3.7/site-packages
Requires: ordered-set, zstandard
Required-by:
