### ISSUE TITLE
nuitka/build/SingleExe.scons: NameError: name '_decode' is not defined

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#423]
https://build.opensuse.org/package/show/home:jayvdb:py-bridge/python-Nuitka-factory

My guess is this is related to the .spec de-vendoring scons

```console
[   72s] +NameError: name '_decode' is not defined:
[   72s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1560187380.a71fcb71/nuitka/build/SingleExe.scons", line 500:
[   72s] +    env = createEnvironment(compiler_tools=compiler_tools)
[   72s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1560187380.a71fcb71/nuitka/build/SingleExe.scons", line 485:
[   72s] +    **args
[   72s] +  File "/usr/lib/python3.7/site-packages/SCons/Environment.py", line 982:
[   72s] +    apply_tools(self, tools, toolpath)
[   72s] +  File "/usr/lib/python3.7/site-packages/SCons/Environment.py", line 107:
[   72s] +    env.Tool(tool)
[   72s] +  File "/usr/lib/python3.7/site-packages/SCons/Environment.py", line 1789:
[   72s] +    tool(self)
[   72s] +  File "/usr/lib/python3.7/site-packages/SCons/Tool/__init__.py", line 296:
[   72s] +    self.generate(env, *args, **kw)
[   72s] +  File "/usr/lib/python3.7/site-packages/SCons/Tool/default.py", line 40:
[   72s] +    for t in SCons.Tool.tool_list(env['PLATFORM'], env):
[   72s] +  File "/usr/lib/python3.7/site-packages/SCons/Tool/__init__.py", line 1266:
[   72s] +    c_compiler = FindTool(c_compilers, env) or c_compilers[0]
[   72s] +  File "/usr/lib/python3.7/site-packages/SCons/Tool/__init__.py", line 1169:
[   72s] +    if t.exists(env):
[   72s] +  File "/usr/lib/python3.7/site-packages/SCons/Tool/gcc.py", line 66:
[   72s] +    return detect_version(env, env.Detect(env.get('CC', compilers)))
[   72s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1560187380.a71fcb71/nuitka/build/SingleExe.scons", line 429:
[   72s] +    gcc_version = detectVersion(self, result)
[   72s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3.1560187380.a71fcb71/nuitka/build/SingleExe.scons", line 378:
[   72s] +    line = _decode(line)
```

**Comment by kayhayen** [comment]
Fixed.

Also, looking at it, the `copy_tree` patch seems unnecessary now, is it not?

And it says 0.6.3 in the tarball name, which I think ought to be more like 0.6.4 or 5.

Yours,
Kay

**Comment by jayvdb** [comment]
Refreshing, will update version and delete unneeded patch.

Please also note tk isnt quite fixed ; see https://github.com/Nuitka/Nuitka/issues/359#issuecomment-499941327

**Comment by jayvdb** [comment]
Fixed.
