### ISSUE TITLE
Visual Studion 2019 not supported by Scons

### ISSUE THREAD

**Issue by AhmedMKamal** [Nuitka/Nuitka#452]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/kayhayen/Nuitka/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.

* Please check out if the develop version of Nuitka works better for you.

  Download source, packages [from here](http://nuitka.net/pages/download.html)
  where you will also find instructions how to do it via PyPI.

If you want to post a problem/bug, to help us understand and resolve your issue
please check that you have provided at least the information below, and discard
up to here:

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

   python -m nuitka --version
   0.6.4
   Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
   OS: Windows
   Arch: x86_64
  wsPython: 4.0

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

   Nuitka and Python both from Windows installers (msi)

*  Many times when you get an error from Nuitka, your setup may be so special
   that even a "hello world" program will not work, please try that and report
   it instead.

*  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
   that demonstrates the issue i.e a small piece of code which reproduces
   the issue and can be run with out any other (or as few as possible)
   external dependencies.

```python
import wx

class MyFrame(wx.Frame):
    def __init__(self):
        super().__init__(self,parent=None, title='Hello World')
        panel = wx.Panel(self)
        self.Show()

if __name__ == '__main__':
    app = wx.App()
    frame = MyFrame()
    app.MainLoop()
```

*  If this is a regression (used to work in an earlier version of Nuitka),
   please note what you know about that.

I'm trying to compile the example above into `exe` using the command `py -m nuitka --follow-imports --standalone example.py` but I'm getting the following error 

```
IndexError: list index out of range:
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\SingleExe.scons", line 500:
    env = createEnvironment(compiler_tools=compiler_tools)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\SingleExe.scons", line 485:
    **args
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Environment.py", line 982:
    apply_tools(self, tools, toolpath)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Environment.py", line 107:
    env.Tool(tool)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Environment.py", line 1789:
    tool(self)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\__init__.py", line 299:
    self.generate(env, *args, **kw)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\default.py", line 40:
    for t in SCons.Tool.tool_list(env['PLATFORM'], env):
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\__init__.py", line 1271:
    c_compiler = FindTool(c_compilers, env) or c_compilers[0]
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\__init__.py", line 1172:
    if t.exists(env):
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\msvc.py", line 292:
    return msvc_exists(env)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 759:
    vcs = cached_get_installed_vcs(env)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 524:
    ret = get_installed_vcs(env)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 535:
    VC_DIR = find_vc_pdir(ver)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 344:
    comps = find_vc_pdir_vswhere(msvc_version)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 306:
    vc_pdir = os.path.join(vsdir[0], 'VC')
```

**Comment by kayhayen** [comment]
This is unfortunate, I think it is because of an issue that Scons has recently fixed, and somebody else has reported this too. Nuitka uses 3.0.4 right now, and 3.0.4 would not have that. The changelog of theirs says:

>    - Fixed bug which threw error when running SCons on windows system with no MSVC installed.

Can you confirm that is the case? And if so, can I convince you to hold off for a relatively short time, so I can update Nuitka to include 3.0.5 and that you can test this to be fixed. For me, a Windows without MSVC is short lived.

Yours,
Kay

**Comment by AhmedMKamal** [comment]
Hi @kayhayen, unfortunately, it's not the case, I have MSVC installed, but I think it worth to mention that I have MSVC version 16 installed, actually I've faced many issues before because of many tools don't support MSVC-16 yet.

**Comment by kayhayen** [comment]
@AhmedMKamal yes, Scons is ignoring that, so you get the crash that means it doesn't find any MSVC.

**Comment by AhmedMKamal** [comment]
@kayhayen so, for now, I have to install MSVC-15 yes?

**Comment by kayhayen** [comment]
@AhmedMKamal if you wait a moment, I will update to Scons 3.0.5, and maybe it does MSVC 16.

Also, I think VS 2017 is 14.1 or something, they screwed with the numbering.

You can also go with MinGW64, which from my cursory testing gives smaller and faster binaries. See #148 reports.

Yours,
Kay

**Comment by AhmedMKamal** [comment]
> if you wait a moment, I will update to Scons 3.0.5, and maybe it does MSVC 16.

yes for sure take your time 😊.

> Also, I think VS 2017 is 14.1 or something, they screwed with the numbering.

VS 2017 is 15 and I have VS 2019 which is 16.

> You can also go with MinGW64

I have MinGW64 installed but I have no idea how to use it with `Nuitka`, I'll refer to the link in your comment and give it a try.

**Comment by kayhayen** [comment]
The user manual explains how to use it. :)

**Comment by kayhayen** [comment]
So I just pushed the tenative scons 3.0.5 update to the factory branch, you are welcome to try it out.

The detection code changed, but I am not good enough at scons to tell if it matters for VS 2019, but at least one Windows SDK version is better detected. Let me know if it changes anything.

And yes, if it fails, VS 2017 is required. But I understand one can install them side by side?

I won't bother with it yet, as it's only a preview version, and I got issues enough with regular MSVC, and from my experience, they never improve anything I care about. :)

Yours,
Kay

**Comment by kayhayen** [comment]
So this is in 0.6.5rc3, currently develop branch.

**Comment by AhmedMKamal** [comment]
Hi @kayhayen, unfortunately, I'm still facing that issue, here's step by step what I've done.

1- switch to factory brunch.
2- download as zip.
3- extract and `py setup.py install`.
4- create a [test file](https://github.com/Nuitka/Nuitka#create-a-folder-for-the-python-code)
5- run `py -m nuitka --standalone hello.py` (not working)
6- try using `mingw64`, again run `py -m nuitka --standalone --mingw64 hello.py` (same issue)

the following is a list of all tools versions I'm using maybe that can help you.

```
Windows 10

// py --version
Python 3.7.3

// py -m nuitka --version
0.6.4
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\enahm\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64

// gcc --version
gcc.exe (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

// MSVC
Visual Studio 2019 v16.2.0-pre.2.0
```

the full error's stack trace

```
IndexError: list index out of range:
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\SingleExe.scons", line 1746:
    os.path.join(source_dir, "cache-" + target_arch + "-" + python_abi_version)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Script\SConscript.py", line 665:
    env = self.factory()
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Script\SConscript.py", line 645:
    default_env = SCons.Defaults.DefaultEnvironment()
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Defaults.py", line 88:
    _default_env = SCons.Environment.Environment(*args, **kw)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Environment.py", line 982:
    apply_tools(self, tools, toolpath)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Environment.py", line 107:
    env.Tool(tool)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Environment.py", line 1789:
    tool(self)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\__init__.py", line 299:
    self.generate(env, *args, **kw)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\default.py", line 40:
    for t in SCons.Tool.tool_list(env['PLATFORM'], env):
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\__init__.py", line 1271:
    c_compiler = FindTool(c_compilers, env) or c_compilers[0]
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\__init__.py", line 1172:
    if t.exists(env):
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\msvc.py", line 292:
    return msvc_exists(env)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 759:
    vcs = cached_get_installed_vcs(env)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 524:
    ret = get_installed_vcs(env)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 535:
    VC_DIR = find_vc_pdir(ver)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 344:
    comps = find_vc_pdir_vswhere(msvc_version)
  File "C:\Users\enahm\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 306:
    vc_pdir = os.path.join(vsdir[0], 'VC')
```

**Comment by kayhayen** [comment]
I am putting this to delayed as Visual Studio 2019 is not yet released. We really won't go to unfinished C compilers, esp. as side by side installation with 2017 is possible. Also dependent on Scons upstream to pick this up.

**Comment by kayhayen** [comment]
Released as 0.6.5 with newer scons that handles this, also VS 2019 is final and works better.
