### ISSUE TITLE
Shapely on Anaconda/Windows 

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#675]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

>  python -m nuitka --version
```
0.6.7
Python: 3.7.6 (default, Jan  8 2020, 16:21:45) [MSC v.1916 32 bit (Intel)]
Executable: C:\anaconda32-3.7\python.exe
OS: Windows
Arch: x86

0.6.6
Python: 3.6.8 |Anaconda custom (64-bit)| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]                                                                 
Executable: C:\Anaconda3\python.EXE
OS: Windows
Arch: x86_64
```

> How did you install Nuitka 
Anaconda + pip install

Code:
```
from shapely.geometry.polygon import Polygon
print('11111')
```

build command:
```
python -m nuitka --recurse-none --standalone shapely-wtf.py --verbose --jobs=4  --recurse-to=shapely --include-package=shapely  --output-dir=w64-wtf
```
See sample files on https://github.com/belonesox/wtf-shapely-nuitka

Building — OK.
Trying to run get  (same bug on Anaconda 32bit python 3.7 and Anaconda python 3.6 x64)

```
Traceback (most recent call last):
  File "C:\projects\nuitka\wtf-shapely-nuitka\w64-wtf\shapely-wtf.dist\shapely-wtf.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\projects\nuitka\wtf-shapely-nuitka\w64-wtf\shapely-wtf.dist\shapely\geometry\__init__.py", line 4, in <module shapely.geometry>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\projects\nuitka\wtf-shapely-nuitka\w64-wtf\shapely-wtf.dist\shapely\geometry\base.py", line 17, in <module shapely.geometry.base>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\projects\nuitka\wtf-shapely-nuitka\w64-wtf\shapely-wtf.dist\shapely\coords.py", line 8, in <module shapely.coords>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\projects\nuitka\wtf-shapely-nuitka\w64-wtf\shapely-wtf.dist\shapely\geos.py", line 125, in <module shapely.geos>
AttributeError: module 'os' has no attribute '__file__'
```
See sample files on https://github.com/belonesox/wtf-shapely-nuitka

On Linux (Fedora, python 3.7) looks OK

**Comment by kayhayen** [comment]
This is fixed on develop already.

**Comment by belonesox** [comment]
Hmm. But still not OK with Python 3.4.4 Windows 32  :(
After building 
( https://github.com/belonesox/wtf-shapely-nuitka/blob/master/!build32-python-344-w32.bat )
got
```
Traceback (most recent call last):
  File "C:\projects\nuitka\WTF-SH~1\PYTHON~1.4-W\SHAPEL~1.DIS\shapely\geos.py", line 119, in <module shapely.geos>
  File "C:\projects\nuitka\WTF-SH~1\PYTHON~1.4-W\SHAPEL~1.DIS\ctypes\__init__.py", line 351, in __init__
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\nuitka\WTF-SH~1\PYTHON~1.4-W\SHAPEL~1.DIS\shapely-wtf.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\projects\nuitka\WTF-SH~1\PYTHON~1.4-W\SHAPEL~1.DIS\shapely\geometry\__init__.py", line 4, in <module shapely.geometry>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\projects\nuitka\WTF-SH~1\PYTHON~1.4-W\SHAPEL~1.DIS\shapely\geometry\base.py", line 17, in <module shapely.geometry.base>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\projects\nuitka\WTF-SH~1\PYTHON~1.4-W\SHAPEL~1.DIS\shapely\coords.py", line 8, in <module shapely.coords>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\projects\nuitka\WTF-SH~1\PYTHON~1.4-W\SHAPEL~1.DIS\shapely\geos.py", line 122, in <module shapely.geos>
  File "C:\projects\nuitka\WTF-SH~1\PYTHON~1.4-W\SHAPEL~1.DIS\ctypes\__init__.py", line 351, in __init__
OSError: [WinError 126] The specified module could not be found
```

Should I push another issue?
