### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import 2020

### ISSUE THREAD

**Issue by italorecife** [Nuitka/Nuitka#738]
versions:
```
0.6.9rc4
Python: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Executable: C:\ProgramData\Anaconda3\python.exe
OS: Windows
Arch: x86_64
```

compiled with:
`python -m nuitka --plugin-enable=numpy --plugin-enable=qt-plugins --mingw64 --standalone --follow-imports --recurse-all teste.py --show-progress --show-scons`

error:
```
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "C:\Users\italo\Desktop\bt\TESTE~1.DIS\teste.py", line 2, in <module>
  File "C:\Users\italo\Desktop\bt\TESTE~1.DIS\python_imagesearch\imagesearch.py", line 1, in <module python_imagesearch.imagesearch>
    import cv2
  File "C:\Users\italo\Desktop\bt\TESTE~1.DIS\cv2\__init__.py", line 5, in <module cv2>
ImportError: numpy.core.multiarray failed to import
```

I've tried several versions of, python, nuitka and numpy, nothing resolves 😢

**Comment by kayhayen** [comment]
Where is the minimal reproducer? Seems you have `teste.py` so please share it.

**Comment by italorecife** [comment]
I am almost a day trying to solve this problem, I have uninstalled and re-installed several possible versions of python and plugins/modules, and I also tried to recompile it in different ways, and it seems that now it was. using Anaconda3 with everything updated 100% in the latest version, I don’t know what did fix, just fixed


could you help me here? : https://github.com/Nuitka/NUITKA-Utilities/issues/42


teste.py:
used: https://github.com/drov0/python-imagesearch
```
from PIL import Image
from python_imagesearch.imagesearch import imagesearch
import pyautogui
import os
import numpy
print(numpy.__version__)

pos = imagesearch('./p1.png')
if pos[0] != -1:
    print("position : ", pos[0], pos[1])
    pyautogui.moveTo(pos[0]+Image.open('./p1.png').size[0]/2,pos[1]+Image.open('./p1.png').size[1]/2)
else:
    print("image not found")
os.system('pause')
```

**Comment by kayhayen** [comment]
Can you confirm the Numpy version where it's working? Because that might have been a symtom of #736 which was just fixed.

**Comment by italorecife** [comment]
it seems that nuitka 0.6.8.3 was not working with numpy 1.18.5, I upgraded nuitka to factory(0.6.9rc4) version and it worked

**Comment by remort** [comment]
Tried numpy versions down to 1.21.0. Nuitka version is 1.0.4. `--follow-import-to=numpy` and `--enable-plugin=numpy` options are present. Still get this error:

```
ModuleNotFoundError: No module named 'numpy'
ImportError: numpy.core.multiarray failed to import
```

**Comment by remort** [comment]
Ok, got some MVPs.
1. Numpy MVP compiles and works fine, no errors in runtime.
2. Onnxruntime MVP, which imports numpy somwhere internally, compiles and run with errors.

Numpy MVP:
```
import numpy
print(numpy.__version__)
```

Onnxruntime MVP:
```
import onnxruntime
print(onnxruntime.__version__)
```

The last gives error:
```
# ./onnxruntime_test.bin 
ModuleNotFoundError: No module named 'numpy'
ImportError: numpy.core.multiarray failed to import
```
