### ISSUE TITLE
Compiler arch not recognized in Windows + Anaconda due to localization of objdump

### ISSUE THREAD

**Issue by psec9000** [Nuitka/Nuitka#800]
Window 7 64 bit, Anaconda3 64 bit, gcc 5.3.0

python -m nuitka --standalone --mingw64 hello.py
> Error, mismatch between Python binary ('D:\data\anaconda3\python.exe' -> 'pei-x86-64') and C compiler ('D:\Data\anaconda3\Library\mingw-w64\bin\gcc.exe' -> '**None**') arches.

The problem is due to the localized output of objdump (italian in this case):
objdump -f d:\data\anaconda3\Library\mingw-w64\bin\gcc.exe 
> d:\data\anaconda3\Library\mingw-w64\bin\gcc.exe:     **formato del file** pei-x86-64
architettura: i386:x86-64, flag 0x00000132:
EXEC_P, HAS_SYMS, HAS_LOCALS, D_PAGED
indirizzo di partenza 0x0000000000401510

Can be fixed in SingleExe.scons, lines 1430-1431:

            if " file format " in line:
                return line.split(" file format ")[-1]

become:

            if line.startswith(binary):
                return line.split()[-1]

**Comment by kayhayen** [comment]
You didn't check develop, did you? I believe that one is fixed there already. That fix just sets `LANG=C` making the output reliable.

**Comment by psec9000** [comment]
Nuitka-0.6.9rc5-py3.7 still fails.
Manually setting LANG=C in the environment does work thoug.
